<?php

namespace App\Console\Commands;

use App\Services\Ai\Programming\Frontend\AtlasFrontendRivalReplayHarnessService;
use Illuminate\Console\Command;
use App\Console\Concerns\EmitsCanonicalJson;

class AtlasFrontendRivalReplayCommand extends Command
{
    use EmitsCanonicalJson;

    protected $signature = 'atlas:frontend:replay
        {action=inspect : inspect, template, runner-kit, evidence-worklist, proof-contract, proof-bundle, operator-packet, operator-packet-verify, score-template, external-receipt-template or apply-patch}
        {--evidence= : Evidence directory for inspect, evidence-worklist, proof-contract, proof-bundle, operator-packet, operator-packet-verify, score-template, external-receipt-template or apply-patch action}
        {--output= : Output directory for template/runner-kit, or output JSON path for evidence-worklist/proof-contract/proof-bundle/operator-packet/operator-packet-verify/score-template/external-receipt-template/apply-patch}
        {--patch= : Provider-safe manifest patch JSON generated by score-template or external-receipt-template}
        {--case= : Replay case id for score-template/external-receipt-template}
        {--system= : Replay system id for score-template/external-receipt-template}
        {--reviewer-ref-hash= : Provider-safe reviewer reference hash for score-template}
        {--scoring-surface=manual_competitive_review : Scoring surface for score-template}
        {--execution-surface=external_rival_system : Execution surface for external-receipt-template}
        {--json : Emit canonical JSON payload}';

    protected $description = 'Inspect, template or operationalize Atlas Frontend external rival replay evidence.';

    public function handle(AtlasFrontendRivalReplayHarnessService $replay): int
    {
        $payload = match ((string) $this->argument('action')) {
            'inspect' => $replay->inspect((string) ($this->option('evidence') ?: '')),
            'template' => $replay->writeTemplate((string) ($this->option('output') ?: '')),
            'runner-kit' => $replay->writeRunnerKit((string) ($this->option('output') ?: '')),
            'evidence-worklist' => $replay->writeEvidenceWorklist((string) ($this->option('evidence') ?: ''), $this->nullableOutput()),
            'proof-contract' => $replay->writeCompetitiveProofContract((string) ($this->option('evidence') ?: ''), $this->nullableOutput()),
            'proof-bundle' => $replay->writeCompetitiveProofBundle((string) ($this->option('evidence') ?: ''), $this->nullableOutput()),
            'operator-packet' => $replay->writeOperatorPacket($this->operatorPacketEvidenceInput(), $this->operatorPacketOutputPath()),
            'operator-packet-verify' => $replay->verifyOperatorPacket((string) ($this->option('evidence') ?: ''), $this->nullableOutput()),
            'score-template' => $replay->writeScoreAttestationTemplate(
                (string) ($this->option('evidence') ?: ''),
                (string) ($this->option('case') ?: ''),
                (string) ($this->option('system') ?: ''),
                $this->nullableOutput(),
                (string) ($this->option('reviewer-ref-hash') ?: ''),
                (string) ($this->option('scoring-surface') ?: ''),
            ),
            'external-receipt-template' => $replay->writeExternalExecutionReceiptTemplate(
                (string) ($this->option('evidence') ?: ''),
                (string) ($this->option('case') ?: ''),
                (string) ($this->option('system') ?: ''),
                $this->nullableOutput(),
                (string) ($this->option('execution-surface') ?: ''),
            ),
            'apply-patch' => $replay->applyManifestPatch(
                (string) ($this->option('evidence') ?: ''),
                (string) ($this->option('patch') ?: ''),
                $this->nullableOutput(),
            ),
            default => [
                'schema_version' => AtlasFrontendRivalReplayHarnessService::SCHEMA_VERSION,
                'status' => 'failed',
                'error' => 'invalid_action',
            ],
        };

        if ((bool) $this->option('json')) {
            $this->line($this->encode($payload));
        } else {
            $this->line('Atlas Frontend Rival Replay: '.$payload['status']);
        }

        return ($payload['status'] ?? null) === 'failed' ? self::FAILURE : self::SUCCESS;
    }

    private function nullableOutput(): ?string
    {
        $output = (string) ($this->option('output') ?? '');
        $output = trim($output);

        return $output === '' ? null : $output;
    }

    private function operatorPacketEvidenceInput(): string
    {
        $evidence = trim((string) ($this->option('evidence') ?? ''));
        if ($evidence !== '') {
            return $evidence;
        }

        return trim((string) ($this->option('output') ?? ''));
    }

    private function operatorPacketOutputPath(): ?string
    {
        return trim((string) ($this->option('evidence') ?? '')) !== ''
            ? $this->nullableOutput()
            : null;
    }
}
