<?php

declare(strict_types=1);

namespace App\Services\Ai\SelfConstruction\Readiness\DispatchGate;

use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorEnablementGateInvoker;
use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorFreshReleaseGateInvoker;
use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartGuardedProcessStartExecutorGateInvoker;
use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartProcessStartEnvelopeGateInvoker;
use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartStartExecutionGateInvoker;
use App\Services\Ai\SelfConstruction\ControlPlane\AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartSupervisedStartActivationGateInvoker;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerExecutorEnablementGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerExecutorFreshReleaseGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerGuardedProcessStartExecutor;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartExecutorEnablementGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartExecutorFreshReleaseGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartGuardedProcessStartExecutorGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartProcessStartEnvelopeGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartStartExecutionGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerPostStartSupervisedStartActivationGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerProcessStartEnvelopeBuilder;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerStartExecutionGate;
use App\Services\Ai\SelfConstruction\Support\AgentCodexRealInvokerSupervisedStartActivationGate;
use App\Services\Ai\SelfConstruction\Readiness\AtlasSelfConstructionReadinessService;

/**
 * DispatchGate sub-section 01 of ReadinessProjectionDispatchGateSection.
 * Method bodies are byte-identical to the pre-split facade (GOD-DEBULK sub-split).
 */
final class DispatchGatePart01SubSection
{
    private ?AtlasSelfConstructionReadinessService $mother = null;

    public function setMother(AtlasSelfConstructionReadinessService $mother): self
    {
        $this->mother = $mother;

        return $this;
    }

    public function __call(string $name, array $arguments): mixed
    {
        if ($this->mother === null) {
            throw new \RuntimeException('DispatchGatePart01SubSection mother not bound for '.$name);
        }
        $method = new \ReflectionMethod($this->mother, $name);

        return $method->invokeArgs($this->mother, $arguments);
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartGuardedProcessStartExecutorGateContract(array $options = []): array
    {
        $activationStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartSupervisedStartActivationGateStatus($options);
        $activationStatus = (array) data_get($activationStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_status', []);
        $postStartGuardedPayload = $this->agentCodexRealInvokerPostStartGuardedProcessStartExecutorGateContractTemplate($options);
        $guardedPayload = $this->agentCodexRealInvokerGuardedProcessStartExecutorContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-GUARDED-PROCESS-START-EXECUTOR-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_supervised_start_activation_gate_status' => data_get($activationStatus, 'status'),
            'source_codex_real_invoker_post_start_supervised_start_activation_gate_status_hash' => data_get($activationStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_status_hash'),
            'source_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_status' => data_get($postStartGuardedPayload, 'status'),
            'source_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_hash' => data_get($postStartGuardedPayload, 'codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_template_hash'),
            'source_codex_real_invoker_guarded_process_start_executor_contract_status' => data_get($guardedPayload, 'status'),
            'source_codex_real_invoker_guarded_process_start_executor_contract_hash' => data_get($guardedPayload, 'codex_real_invoker_guarded_process_start_executor_contract_template_hash'),
            'guarded_process_start' => [
                'canonical_post_start_guarded_process_start_executor_gate' => AgentCodexRealInvokerPostStartGuardedProcessStartExecutorGate::class,
                'canonical_post_start_guarded_process_start_executor_gate_method' => 'preparePostStartGuardedProcessStart',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartGuardedProcessStartExecutorGateInvoker::class,
                'scheduler_invoker_method' => 'prepareCodexRealInvokerPostStartGuardedProcessStartExecutorGate',
                'generic_guarded_process_start_executor' => AgentCodexRealInvokerGuardedProcessStartExecutor::class,
                'generic_guarded_process_start_executor_method' => 'prepareGuardedStart',
                'post_start_supervised_start_activation_required_before_guarded_process_start' => true,
                'post_start_evidence_acceptance_bridge_required_before_guarded_process_start' => true,
                'provider_start_supervised_activation_required_before_guarded_process_start' => true,
                'gate_delegates_to_codex_real_invoker_guarded_process_start_executor' => true,
                'process_start_armed_by_contract' => true,
                'guarded_process_start_is_not_process_start' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_guarded_process_start_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_guarded_process_start_gate_id',
                'post_start_supervised_start_activation_gate_id',
                'post_start_evidence_acceptance_bridge_id',
                'post_start_executor_enablement_gate_id',
                'post_start_executor_fresh_release_gate_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'real_invoker_executor_enablement_id',
                'real_invoker_supervised_start_activation_id',
                'real_invoker_guarded_process_start_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'signed_dispatch_receipt_hash',
                'operator_release_receipt_hash',
                'operator_spawn_receipt_hash',
                'operator_final_spawn_receipt_hash',
                'operator_runtime_receipt_hash',
                'operator_invocation_receipt_hash',
                'operator_dry_run_receipt_hash',
                'operator_release_preflight_receipt_hash',
                'operator_signed_release_receipt_hash',
                'operator_implementation_boundary_receipt_hash',
                'operator_executor_plan_receipt_hash',
                'operator_fresh_release_receipt_hash',
                'operator_enablement_receipt_hash',
                'operator_start_activation_receipt_hash',
                'operator_guarded_start_receipt_hash',
                'enablement_policy_hash',
                'pre_start_checklist_hash',
                'disable_switch_hash',
                'start_window_hash',
                'process_start_guard_hash',
                'supervisor_observer_hash',
                'pid_guard_hash',
                'cwd_integrity_hash',
                'process_runner_contract_hash',
                'dry_run_rehearsal_hash',
                'launch_invocation_contract_hash',
                'post_start_observability_hash',
                'revoke_guard_hash',
                'plan_revalidation_report_hash',
                'freshness_window_hash',
                'final_human_signature_hash',
                'signature_verification_report_hash',
                'codex_execution_contract_hash',
                'supervised_start_contract_hash',
                'runtime_supervision_plan_hash',
                'stdout_stderr_sink_hash',
                'liveness_probe_hash',
                'runtime_driver_contract_hash',
                'invoker_contract_hash',
                'real_invoker_contract_hash',
                'release_policy_hash',
                'implementation_plan_hash',
                'executor_binary_contract_hash',
                'executor_observability_contract_hash',
                'process_command_hash',
                'environment_contract_hash',
                'termination_policy_hash',
                'rollback_plan_hash',
                'max_runtime_policy_hash',
                'actor',
                'session',
                'reason',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_guarded_process_start_metadata_on_provider_start_run',
                'append_codex_real_invoker_guarded_process_start_evidence_event',
                'record_codex_real_invoker_post_start_guarded_process_start_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'authorize_final_process_start_without_separate_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_guarded_process_start_executor_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'process_start_armed' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_guarded_process_start_executor_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start guarded process start executor gate contract is ready; it scopes guarded process start metadata and still forbids actual process start.',
        ];
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartSupervisedStartActivationGateContract(array $options = []): array
    {
        $enablementStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorEnablementGateStatus($options);
        $enablementStatus = (array) data_get($enablementStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_status', []);
        $postStartActivationPayload = $this->agentCodexRealInvokerPostStartSupervisedStartActivationGateContractTemplate($options);
        $activationPayload = $this->agentCodexRealInvokerSupervisedStartActivationGateContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-SUPERVISED-START-ACTIVATION-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_executor_enablement_gate_status' => data_get($enablementStatus, 'status'),
            'source_codex_real_invoker_post_start_executor_enablement_gate_status_hash' => data_get($enablementStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_status_hash'),
            'source_codex_real_invoker_post_start_supervised_start_activation_gate_contract_status' => data_get($postStartActivationPayload, 'status'),
            'source_codex_real_invoker_post_start_supervised_start_activation_gate_contract_hash' => data_get($postStartActivationPayload, 'codex_real_invoker_post_start_supervised_start_activation_gate_contract_template_hash'),
            'source_codex_real_invoker_supervised_start_activation_gate_contract_status' => data_get($activationPayload, 'status'),
            'source_codex_real_invoker_supervised_start_activation_gate_contract_hash' => data_get($activationPayload, 'codex_real_invoker_supervised_start_activation_gate_contract_template_hash'),
            'activation' => [
                'canonical_post_start_supervised_start_activation_gate' => AgentCodexRealInvokerPostStartSupervisedStartActivationGate::class,
                'canonical_post_start_supervised_start_activation_gate_method' => 'preparePostStartSupervisedStartActivation',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartSupervisedStartActivationGateInvoker::class,
                'scheduler_invoker_method' => 'prepareCodexRealInvokerPostStartSupervisedStartActivationGate',
                'generic_supervised_start_activation_gate' => AgentCodexRealInvokerSupervisedStartActivationGate::class,
                'generic_supervised_start_activation_gate_method' => 'prepareActivation',
                'post_start_executor_enablement_required_before_activation' => true,
                'post_start_evidence_acceptance_bridge_required_before_activation' => true,
                'provider_start_enablement_required_before_activation' => true,
                'gate_delegates_to_codex_real_invoker_supervised_start_activation_gate' => true,
                'process_start_armed_by_contract' => true,
                'activation_is_not_process_start' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_supervised_start_activation_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_supervised_start_activation_gate_id',
                'post_start_executor_enablement_gate_id',
                'post_start_evidence_acceptance_bridge_id',
                'post_start_executor_fresh_release_gate_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'real_invoker_executor_enablement_id',
                'real_invoker_supervised_start_activation_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'signed_dispatch_receipt_hash',
                'operator_release_receipt_hash',
                'operator_spawn_receipt_hash',
                'operator_final_spawn_receipt_hash',
                'operator_runtime_receipt_hash',
                'operator_invocation_receipt_hash',
                'operator_dry_run_receipt_hash',
                'operator_release_preflight_receipt_hash',
                'operator_signed_release_receipt_hash',
                'operator_implementation_boundary_receipt_hash',
                'operator_executor_plan_receipt_hash',
                'operator_fresh_release_receipt_hash',
                'operator_enablement_receipt_hash',
                'operator_start_activation_receipt_hash',
                'enablement_policy_hash',
                'pre_start_checklist_hash',
                'disable_switch_hash',
                'start_window_hash',
                'process_start_guard_hash',
                'supervisor_observer_hash',
                'pid_guard_hash',
                'cwd_integrity_hash',
                'plan_revalidation_report_hash',
                'freshness_window_hash',
                'final_human_signature_hash',
                'signature_verification_report_hash',
                'codex_execution_contract_hash',
                'supervised_start_contract_hash',
                'runtime_supervision_plan_hash',
                'stdout_stderr_sink_hash',
                'liveness_probe_hash',
                'runtime_driver_contract_hash',
                'invoker_contract_hash',
                'real_invoker_contract_hash',
                'release_policy_hash',
                'implementation_plan_hash',
                'executor_binary_contract_hash',
                'executor_observability_contract_hash',
                'process_command_hash',
                'environment_contract_hash',
                'termination_policy_hash',
                'rollback_plan_hash',
                'max_runtime_policy_hash',
                'actor',
                'session',
                'reason',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_supervised_start_activation_metadata_on_provider_start_run',
                'append_codex_real_invoker_supervised_start_activation_evidence_event',
                'record_codex_real_invoker_post_start_supervised_start_activation_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'authorize_guarded_process_start_without_separate_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_supervised_start_activation_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_supervised_start_activation_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'process_start_armed' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_supervised_start_activation_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start supervised start activation gate contract is ready; it scopes activation metadata and still forbids process start.',
        ];
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartProcessStartEnvelopeGateContract(array $options = []): array
    {
        $rehearsalStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartActualProcessStartRehearsalGateStatus($options);
        $rehearsalStatus = (array) data_get($rehearsalStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_actual_process_start_rehearsal_gate_status', []);
        $postStartEnvelopePayload = $this->agentCodexRealInvokerPostStartProcessStartEnvelopeGateContractTemplate($options);
        $envelopeBuilderPayload = $this->agentCodexRealInvokerProcessStartEnvelopeBuilderContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-PROCESS-START-ENVELOPE-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_actual_process_start_rehearsal_gate_status' => data_get($rehearsalStatus, 'status'),
            'source_codex_real_invoker_post_start_actual_process_start_rehearsal_gate_status_hash' => data_get($rehearsalStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_actual_process_start_rehearsal_gate_status_hash'),
            'source_codex_real_invoker_post_start_process_start_envelope_gate_contract_status' => data_get($postStartEnvelopePayload, 'status'),
            'source_codex_real_invoker_post_start_process_start_envelope_gate_contract_hash' => data_get($postStartEnvelopePayload, 'codex_real_invoker_post_start_process_start_envelope_gate_contract_template_hash'),
            'source_codex_real_invoker_process_start_envelope_builder_contract_status' => data_get($envelopeBuilderPayload, 'status'),
            'source_codex_real_invoker_process_start_envelope_builder_contract_hash' => data_get($envelopeBuilderPayload, 'codex_real_invoker_process_start_envelope_builder_contract_template_hash'),
            'process_start_envelope' => [
                'canonical_post_start_process_start_envelope_gate' => AgentCodexRealInvokerPostStartProcessStartEnvelopeGate::class,
                'canonical_post_start_process_start_envelope_gate_method' => 'buildPostStartProcessStartEnvelope',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartProcessStartEnvelopeGateInvoker::class,
                'scheduler_invoker_method' => 'prepareCodexRealInvokerPostStartProcessStartEnvelopeGate',
                'generic_process_start_envelope_builder' => AgentCodexRealInvokerProcessStartEnvelopeBuilder::class,
                'generic_process_start_envelope_builder_method' => 'buildStartEnvelope',
                'post_start_actual_process_start_rehearsal_required_before_envelope' => true,
                'post_start_evidence_acceptance_bridge_required_before_envelope' => true,
                'provider_start_rehearsal_required_before_envelope' => true,
                'gate_delegates_to_codex_real_invoker_process_start_envelope_builder' => true,
                'process_start_envelope_built_by_contract' => true,
                'envelope_is_not_actual_process_start' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'process_started_by_contract' => false,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_process_start_envelope_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_process_start_envelope_gate_id',
                'post_start_actual_process_start_rehearsal_gate_id',
                'post_start_evidence_acceptance_bridge_id',
                'post_start_final_process_start_authorization_gate_id',
                'post_start_guarded_process_start_gate_id',
                'post_start_supervised_start_activation_gate_id',
                'post_start_executor_enablement_gate_id',
                'post_start_executor_fresh_release_gate_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'real_invoker_executor_enablement_id',
                'real_invoker_supervised_start_activation_id',
                'real_invoker_guarded_process_start_id',
                'real_invoker_final_process_start_authorization_id',
                'real_invoker_actual_process_start_rehearsal_id',
                'real_invoker_process_start_envelope_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'process_start_envelope_hash',
                'start_command_hash',
                'start_environment_hash',
                'start_cwd_hash',
                'start_supervisor_hash',
                'start_liveness_contract_hash',
                'process_start_rehearsal_hash',
                'command_resolution_hash',
                'environment_resolution_hash',
                'cwd_verification_hash',
                'supervisor_dry_run_hash',
                'liveness_probe_rehearsal_hash',
                'operator_final_start_receipt_hash',
                'final_start_signature_hash',
                'final_start_policy_hash',
                'final_start_window_hash',
                'final_start_replay_guard_hash',
                'final_start_kill_switch_hash',
                'actor',
                'session',
                'reason',
            ],
            'forbidden_true_input_flags' => [
                'actual_process_start_allowed',
                'provider_process_call_allowed',
                'adapter_invocation_allowed',
                'adapter_execution_allowed',
                'token_spend_allowed',
                'dispatch_allowed',
                'self_programming_allowed',
                'external_process_started',
                'provider_started',
                'process_started',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_process_start_envelope_metadata_on_provider_start_run',
                'append_codex_real_invoker_process_start_envelope_evidence_event',
                'record_codex_real_invoker_post_start_process_start_envelope_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'execute_start_without_separate_start_execution_gate_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_process_start_envelope_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_process_start_envelope_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'process_start_armed' => false,
            'process_started' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'self_programming_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start process start envelope gate contract is ready; it prepares the final start envelope while real process start, dispatch, token spend, adapter execution and self-programming stay disabled.',
        ];
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorEnablementGateContract(array $options = []): array
    {
        $freshReleaseStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorFreshReleaseGateStatus($options);
        $freshReleaseStatus = (array) data_get($freshReleaseStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_status', []);
        $enablementPayload = $this->agentCodexRealInvokerPostStartExecutorEnablementGateContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-EXECUTOR-ENABLEMENT-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_executor_fresh_release_gate_status' => data_get($freshReleaseStatus, 'status'),
            'source_codex_real_invoker_post_start_executor_fresh_release_gate_status_hash' => data_get($freshReleaseStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_status_hash'),
            'source_codex_real_invoker_post_start_executor_enablement_gate_status' => data_get($enablementPayload, 'status'),
            'source_codex_real_invoker_post_start_executor_enablement_gate_hash' => data_get($enablementPayload, 'codex_real_invoker_post_start_executor_enablement_gate_contract_template_hash'),
            'enablement' => [
                'canonical_post_start_executor_enablement_gate' => AgentCodexRealInvokerPostStartExecutorEnablementGate::class,
                'canonical_post_start_executor_enablement_gate_method' => 'enablePostStartExecutor',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorEnablementGateInvoker::class,
                'scheduler_invoker_method' => 'enableCodexRealInvokerPostStartExecutorGate',
                'codex_real_invoker_executor_enablement_gate_service' => AgentCodexRealInvokerExecutorEnablementGate::class,
                'codex_real_invoker_executor_enablement_gate_method' => 'enableExecutor',
                'enablement_effect' => 'enable_post_start_executor_metadata_without_starting_codex',
                'post_start_executor_fresh_release_required_before_enablement' => true,
                'post_start_evidence_acceptance_bridge_required_before_enablement' => true,
                'provider_start_run_with_codex_real_invoker_executor_fresh_release_required_before_enablement' => true,
                'operator_enablement_receipt_hash_required' => true,
                'enablement_policy_hash_required' => true,
                'pre_start_checklist_hash_required' => true,
                'disable_switch_hash_required' => true,
                'gate_delegates_to_codex_real_invoker_executor_enablement_gate' => true,
                'gate_records_codex_real_invoker_executor_enablement_metadata_on_provider_start_run' => true,
                'gate_records_bridge_metadata_on_observed_run' => true,
                'supervised_start_required_after_enablement' => true,
                'enablement_is_not_process_start' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'executor_enabled_by_contract' => true,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_executor_enablement_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_executor_enablement_gate_id',
                'post_start_executor_fresh_release_gate_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'post_start_evidence_acceptance_bridge_id',
                'real_invoker_executor_enablement_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'signed_dispatch_receipt_hash',
                'operator_release_receipt_hash',
                'operator_spawn_receipt_hash',
                'operator_final_spawn_receipt_hash',
                'operator_runtime_receipt_hash',
                'operator_invocation_receipt_hash',
                'operator_dry_run_receipt_hash',
                'operator_release_preflight_receipt_hash',
                'operator_signed_release_receipt_hash',
                'operator_implementation_boundary_receipt_hash',
                'operator_executor_plan_receipt_hash',
                'operator_fresh_release_receipt_hash',
                'operator_enablement_receipt_hash',
                'enablement_policy_hash',
                'pre_start_checklist_hash',
                'disable_switch_hash',
                'plan_revalidation_report_hash',
                'freshness_window_hash',
                'final_human_signature_hash',
                'signature_verification_report_hash',
                'codex_execution_contract_hash',
                'supervised_start_contract_hash',
                'runtime_supervision_plan_hash',
                'stdout_stderr_sink_hash',
                'liveness_probe_hash',
                'runtime_driver_contract_hash',
                'invoker_contract_hash',
                'real_invoker_contract_hash',
                'release_policy_hash',
                'implementation_plan_hash',
                'executor_binary_contract_hash',
                'executor_observability_contract_hash',
                'process_command_hash',
                'environment_contract_hash',
                'termination_policy_hash',
                'rollback_plan_hash',
                'max_runtime_policy_hash',
                'actor',
                'session',
                'reason',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_executor_enablement_metadata_on_provider_start_run',
                'append_codex_real_invoker_executor_enablement_evidence_event',
                'record_codex_real_invoker_post_start_executor_enablement_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'authorize_supervised_start_without_separate_contract',
                'authorize_actual_process_start_without_separate_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_executor_enablement_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_executor_enablement_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_enablement_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start executor enablement gate contract is ready; it scopes executor enablement metadata and still forbids process start.',
        ];
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartStartExecutionGateContract(array $options = []): array
    {
        $envelopeStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartProcessStartEnvelopeGateStatus($options);
        $envelopeStatus = (array) data_get($envelopeStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_status', []);
        $postStartStartExecutionPayload = $this->agentCodexRealInvokerPostStartStartExecutionGateContractTemplate($options);
        $startExecutionPayload = $this->agentCodexRealInvokerStartExecutionGateContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-START-EXECUTION-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_process_start_envelope_gate_status' => data_get($envelopeStatus, 'status'),
            'source_codex_real_invoker_post_start_process_start_envelope_gate_status_hash' => data_get($envelopeStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_process_start_envelope_gate_status_hash'),
            'source_codex_real_invoker_post_start_start_execution_gate_contract_status' => data_get($postStartStartExecutionPayload, 'status'),
            'source_codex_real_invoker_post_start_start_execution_gate_contract_hash' => data_get($postStartStartExecutionPayload, 'codex_real_invoker_post_start_start_execution_gate_contract_template_hash'),
            'source_codex_real_invoker_start_execution_gate_contract_status' => data_get($startExecutionPayload, 'status'),
            'source_codex_real_invoker_start_execution_gate_contract_hash' => data_get($startExecutionPayload, 'codex_real_invoker_start_execution_gate_contract_template_hash'),
            'start_execution_gate' => [
                'canonical_post_start_start_execution_gate' => AgentCodexRealInvokerPostStartStartExecutionGate::class,
                'canonical_post_start_start_execution_gate_method' => 'authorizePostStartStartExecution',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartStartExecutionGateInvoker::class,
                'scheduler_invoker_method' => 'prepareCodexRealInvokerPostStartStartExecutionGate',
                'generic_start_execution_gate' => AgentCodexRealInvokerStartExecutionGate::class,
                'generic_start_execution_gate_method' => 'authorizeStartExecution',
                'post_start_process_start_envelope_required_before_start_execution' => true,
                'post_start_evidence_acceptance_bridge_required_before_start_execution' => true,
                'provider_start_envelope_required_before_start_execution' => true,
                'gate_delegates_to_codex_real_invoker_start_execution_gate' => true,
                'start_execution_authorized_by_contract' => true,
                'start_execution_authorization_is_not_actual_process_start' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'process_started_by_contract' => false,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_start_execution_gate_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_start_execution_gate_id',
                'post_start_process_start_envelope_gate_id',
                'post_start_evidence_acceptance_bridge_id',
                'post_start_actual_process_start_rehearsal_gate_id',
                'post_start_final_process_start_authorization_gate_id',
                'post_start_guarded_process_start_gate_id',
                'post_start_supervised_start_activation_gate_id',
                'post_start_executor_enablement_gate_id',
                'post_start_executor_fresh_release_gate_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'real_invoker_executor_enablement_id',
                'real_invoker_supervised_start_activation_id',
                'real_invoker_guarded_process_start_id',
                'real_invoker_final_process_start_authorization_id',
                'real_invoker_actual_process_start_rehearsal_id',
                'real_invoker_process_start_envelope_id',
                'real_invoker_start_execution_gate_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'operator_execution_gate_receipt_hash',
                'execution_gate_policy_hash',
                'execution_window_hash',
                'preflight_snapshot_hash',
                'rollback_readiness_hash',
                'human_start_signature_hash',
                'process_start_envelope_hash',
                'start_command_hash',
                'start_environment_hash',
                'start_cwd_hash',
                'start_supervisor_hash',
                'start_liveness_contract_hash',
                'actor',
                'session',
                'reason',
            ],
            'forbidden_true_input_flags' => [
                'actual_process_start_allowed',
                'provider_process_call_allowed',
                'adapter_invocation_allowed',
                'adapter_execution_allowed',
                'token_spend_allowed',
                'dispatch_allowed',
                'self_programming_allowed',
                'external_process_started',
                'provider_started',
                'process_started',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_start_execution_gate_metadata_on_provider_start_run',
                'append_codex_real_invoker_start_execution_gate_evidence_event',
                'record_codex_real_invoker_post_start_start_execution_gate_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'start_actual_process_without_separate_process_starter_readiness_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_start_execution_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_start_execution_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'process_start_armed' => false,
            'process_started' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'self_programming_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_start_execution_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start start execution gate contract is ready; it formalizes the start execution authorization while real process start, dispatch, token spend, adapter execution, process_started and self-programming stay disabled.',
        ];
    }


    /**
     * @param  array{workspace?: string|null, target?: string|null, actor?: string|null, session?: string|null, packet?: string|null, receipt_hash?: string|null}  $options
     * @return array<string, mixed>
     */
    public function agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorFreshReleaseGateContract(array $options = []): array
    {
        $executorPlanStatusPayload = $this->agentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorPlanGateStatus($options);
        $executorPlanStatus = (array) data_get($executorPlanStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_plan_gate_status', []);
        $freshReleasePayload = $this->agentCodexRealInvokerPostStartExecutorFreshReleaseGateContractTemplate($options);

        $contract = [
            'status' => 'one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_ready',
            'contract_id' => 'AGENT-AUTOMATIC-DISPATCH-SCHEDULER-ONE-SHOT-TICK-CODEX-REAL-INVOKER-POST-START-EXECUTOR-FRESH-RELEASE-GATE-CONTRACT-SELF-CONSTRUCTION-0001',
            'parent_program' => 'Atlas Self-Construction OS',
            'submodule' => 'Atlas Agent Control Plane',
            'provider' => 'codex',
            'adapter' => 'codex',
            'source_codex_real_invoker_post_start_executor_plan_gate_status' => data_get($executorPlanStatus, 'status'),
            'source_codex_real_invoker_post_start_executor_plan_gate_status_hash' => data_get($executorPlanStatusPayload, 'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_plan_gate_status_hash'),
            'source_codex_real_invoker_post_start_executor_fresh_release_gate_status' => data_get($freshReleasePayload, 'status'),
            'source_codex_real_invoker_post_start_executor_fresh_release_gate_hash' => data_get($freshReleasePayload, 'codex_real_invoker_post_start_executor_fresh_release_gate_contract_template_hash'),
            'fresh_release' => [
                'canonical_post_start_executor_fresh_release_gate' => AgentCodexRealInvokerPostStartExecutorFreshReleaseGate::class,
                'canonical_post_start_executor_fresh_release_gate_method' => 'authorizePostStartExecutorFreshRelease',
                'scheduler_invoker' => AgentAutomaticDispatchSchedulerOneShotTickCodexRealInvokerPostStartExecutorFreshReleaseGateInvoker::class,
                'scheduler_invoker_method' => 'authorizeCodexRealInvokerPostStartExecutorFreshReleaseGate',
                'codex_real_invoker_executor_fresh_release_gate_service' => AgentCodexRealInvokerExecutorFreshReleaseGate::class,
                'codex_real_invoker_executor_fresh_release_gate_method' => 'authorizeFreshRelease',
                'fresh_release_effect' => 'authorize_post_start_executor_fresh_release_without_enabling_executor',
                'post_start_executor_plan_required_before_fresh_release' => true,
                'post_start_evidence_acceptance_bridge_required_before_fresh_release' => true,
                'provider_start_run_with_codex_real_invoker_executor_plan_required_before_fresh_release' => true,
                'operator_fresh_release_receipt_hash_required' => true,
                'plan_revalidation_report_hash_required' => true,
                'freshness_window_hash_required' => true,
                'final_human_signature_hash_required' => true,
                'gate_delegates_to_codex_real_invoker_executor_fresh_release_gate' => true,
                'gate_records_codex_real_invoker_executor_fresh_release_metadata_on_provider_start_run' => true,
                'gate_records_bridge_metadata_on_observed_run' => true,
                'executor_enablement_required_after_fresh_release' => true,
                'fresh_release_is_not_executor_enablement' => true,
                'actual_process_start_allowed_by_contract' => false,
                'external_process_started_by_contract' => false,
                'provider_process_call_allowed_by_contract' => false,
                'provider_started_by_contract' => false,
                'executor_enabled_by_contract' => false,
                'adapter_invocation_allowed_by_contract' => false,
                'adapter_execution_allowed_by_contract' => false,
                'token_spend_allowed_by_contract' => false,
                'dispatch_allowed_by_contract' => false,
                'idempotency_key' => 'real_invoker_executor_fresh_release_id',
            ],
            'required_input_fields_for_future_invoker' => [
                'run_key',
                'post_start_executor_fresh_release_gate_id',
                'post_start_evidence_acceptance_bridge_id',
                'post_start_executor_plan_gate_id',
                'post_start_implementation_boundary_gate_id',
                'post_start_signed_real_invoker_release_gate_id',
                'post_start_real_invoker_release_preflight_gate_id',
                'post_start_external_process_invoker_dry_run_gate_id',
                'post_start_process_invocation_authorization_gate_id',
                'post_start_external_process_runtime_gate_id',
                'post_start_final_process_spawn_executor_gate_id',
                'post_start_process_spawn_enablement_gate_id',
                'post_start_supervised_start_gate_id',
                'post_start_process_start_release_gate_id',
                'process_start_release_id',
                'provider_execution_contract_gate_id',
                'codex_execution_id',
                'supervised_start_id',
                'spawn_enablement_id',
                'spawn_executor_id',
                'runtime_driver_id',
                'invocation_authorization_id',
                'dry_run_id',
                'real_invoker_release_preflight_id',
                'signed_real_invoker_release_id',
                'real_invoker_implementation_boundary_id',
                'real_invoker_executor_plan_id',
                'real_invoker_executor_fresh_release_id',
                'adapter_execution_guard_gate_id',
                'execution_guard_id',
                'adapter_invocation_boundary_gate_id',
                'adapter_invocation_id',
                'provider_start_driver_gate_id',
                'provider_start_attempt_id',
                'signed_dispatch_receipt_hash',
                'operator_release_receipt_hash',
                'operator_spawn_receipt_hash',
                'operator_final_spawn_receipt_hash',
                'operator_runtime_receipt_hash',
                'operator_invocation_receipt_hash',
                'operator_dry_run_receipt_hash',
                'operator_release_preflight_receipt_hash',
                'operator_signed_release_receipt_hash',
                'operator_implementation_boundary_receipt_hash',
                'operator_executor_plan_receipt_hash',
                'operator_fresh_release_receipt_hash',
                'plan_revalidation_report_hash',
                'freshness_window_hash',
                'final_human_signature_hash',
                'signature_verification_report_hash',
                'codex_execution_contract_hash',
                'supervised_start_contract_hash',
                'runtime_supervision_plan_hash',
                'stdout_stderr_sink_hash',
                'liveness_probe_hash',
                'runtime_driver_contract_hash',
                'invoker_contract_hash',
                'real_invoker_contract_hash',
                'release_policy_hash',
                'implementation_plan_hash',
                'executor_binary_contract_hash',
                'executor_observability_contract_hash',
                'process_command_hash',
                'environment_contract_hash',
                'termination_policy_hash',
                'rollback_plan_hash',
                'max_runtime_policy_hash',
                'actor',
                'session',
                'reason',
            ],
            'allowed_future_mutations' => [
                'record_codex_real_invoker_executor_fresh_release_metadata_on_provider_start_run',
                'append_codex_real_invoker_executor_fresh_release_evidence_event',
                'record_codex_real_invoker_post_start_executor_fresh_release_metadata_on_observed_run',
            ],
            'forbidden_even_after_contract' => [
                'invoke_codex_process',
                'spawn_shell_or_subprocess',
                'call_codex_cli_or_codex_app',
                'run_real_external_process_invoker',
                'dispatch_work_to_codex',
                'send_prompt_to_provider',
                'call_provider_process',
                'enable_executor',
                'enable_adapter_execution',
                'spend_provider_tokens',
                'mark_observed_run_running_or_terminal',
                'authorize_executor_enablement_without_separate_contract',
                'enable_self_programming',
            ],
            'next_required_slice' => 'activate_signed_one_shot_scheduler_tick_codex_real_invoker_post_start_executor_fresh_release_gate_preflight',
        ];

        return [
            'schema_version' => 'atlas.self_construction_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract.v1',
            'status' => (string) $contract['status'],
            'mode' => 'read_only_agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract',
            'execution_allowed' => false,
            'dispatch_allowed' => false,
            'ledger_write_allowed' => false,
            'runtime_write_allowed' => false,
            'post_start_executor_fresh_release_gate_allowed' => false,
            'actual_process_start_allowed' => false,
            'provider_process_call_allowed' => false,
            'executor_enabled' => false,
            'adapter_invocation_allowed' => false,
            'adapter_execution_allowed' => false,
            'token_spend_allowed' => false,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract' => $contract,
            'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_hash' => $this->stableHash($contract),
            'non_execution_guarantees' => [
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_start_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_call_codex',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_enable_executor',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_execute_adapter',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_spend_tokens',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_dispatch_work',
                'agent_automatic_dispatch_scheduler_one_shot_tick_codex_real_invoker_post_start_executor_fresh_release_gate_contract_does_not_enable_self_programming',
            ],
            'human_summary' => 'Automatic dispatch scheduler one-shot tick Codex real invoker post-start executor fresh release gate contract is ready; it authorizes fresh release metadata only and still requires executor enablement.',
        ];
    }


}
