<?php

declare(strict_types=1);

namespace Tests\Unit\CodeGraph;

use App\Services\Engineering\CodeGraph\CodeGraphAdjacencyIndex;
use App\Services\Engineering\CodeGraph\CodeGraphContextPackAssembler;
use Tests\TestCase;

/**
 * AP-815 · D-3 — performance-regression BUDGET tests for the code-graph hot path.
 *
 * Purpose: a CI tripwire. These tests do NOT measure a precise benchmark — they assert
 * that building the adjacency index over a realistically large edge set, and querying
 * it, stay under DELIBERATELY GENEROUS wall-clock ceilings. A healthy build/query is
 * orders of magnitude faster than the ceilings here; the ceilings exist only to FAIL CI
 * on a CATASTROPHIC (≈10x+) latency/throughput regression — e.g. someone accidentally
 * making {@see CodeGraphAdjacencyIndex::neighbors()} re-walk all edges (O(E) per lookup)
 * instead of the O(1)-ish map read it is today.
 *
 * Non-flaky by construction (house contract):
 *   - Input is FULLY DETERMINISTIC: edges are generated by pure modular arithmetic over
 *     loop indices. No mt_rand, no faker, no clock-seeded data — the same edge set every
 *     run, so a failure is a real regression, never a noisy seed.
 *   - Ceilings are LITERAL and GENEROUS (seconds, not milliseconds) with wide headroom
 *     over the real cost on a developer laptop or a slow shared CI box. Micro-noise,
 *     GC pauses, and a loaded CI runner cannot trip them; only a true algorithmic
 *     collapse can.
 *   - Wall-clock is read with microtime(true) immediately around the operation under
 *     test (and nothing else), so the measured window is the operation, not setup.
 *
 * Memory note: the suite's base {@see TestCase} resets memory_limit to the phpunit.xml
 * baseline (4096M) at the start of every test, so this fixture (50k edges / ~10k nodes,
 * a few MB) has ample headroom regardless of any prior test's in-process clamp.
 */
class CodeGraphPerformanceBudgetTest extends TestCase
{
    /**
     * Synthetic graph size. Large enough that an O(E)-per-lookup regression would blow
     * the lookup ceiling spectacularly, small enough to build in well under a second on
     * healthy code (a few MB of arrays). Deterministic — these are fixed constants.
     */
    private const EDGE_COUNT = 50000;

    private const NODE_COUNT = 10000;

    /**
     * GENEROUS ceiling for building the whole index from 50k edges. Real cost is sub-
     * second; 5.0s catches a ~10x+ collapse without ever tripping on laptop/CI noise.
     */
    private const BUILD_CEILING_SECONDS = 5.0;

    /**
     * GENEROUS ceiling for a batch of 10k neighbors() lookups. If each lookup were O(E)
     * (re-walking 50k edges) this would be ~5e8 operations and blow far past 2.0s; the
     * O(1)-ish map read it actually is finishes in a fraction of a second.
     */
    private const NEIGHBORS_BATCH_CEILING_SECONDS = 2.0;

    /**
     * GENEROUS ceiling for packing a large ranked candidate set under a token budget
     * (a single in-order pass). 2.0s catches a quadratic regression in the packer.
     */
    private const PACK_CEILING_SECONDS = 2.0;

    /**
     * Build a deterministic edge set: EDGE_COUNT edges spread over NODE_COUNT nodes via
     * pure modular arithmetic. Every node id is `n{index}`. Node `n{i}` points at
     * `n{(i * 7 + 3) % NODE_COUNT}` — a fixed, dependency-free fan-out pattern that
     * (a) touches every node as a source, (b) produces a dense reusable structure, and
     * (c) is byte-identical on every run. NO randomness.
     *
     * @return list<array{from_node_id: string, to_node_id: string}>
     */
    private function deterministicEdges(): array
    {
        $edges = [];
        for ($i = 0; $i < self::EDGE_COUNT; $i++) {
            $from = $i % self::NODE_COUNT;
            $to = ($i * 7 + 3) % self::NODE_COUNT;
            $edges[] = [
                'from_node_id' => 'n'.$from,
                'to_node_id' => 'n'.$to,
            ];
        }

        return $edges;
    }

    /**
     * fromEdges() over 50k edges / ~10k nodes must build under a generous ceiling, and
     * the resulting index must be structurally correct (a fast-but-broken build is still
     * a failure). Times ONLY the build with microtime(true).
     */
    public function test_fromEdges_builds_large_graph_under_budget(): void
    {
        // Ensure the default node ceiling (200k) is in force so the cap never silently
        // drops nodes from our 10k-node fixture during this timing.
        config()->set('atlas.code_graph.max_adjacency_nodes', CodeGraphAdjacencyIndex::DEFAULT_MAX_NODES);

        $edges = $this->deterministicEdges();
        $this->assertCount(self::EDGE_COUNT, $edges, 'fixture must have exactly the declared edge count');

        $start = microtime(true);
        $index = CodeGraphAdjacencyIndex::fromEdges($edges);
        $elapsed = microtime(true) - $start;

        // The budget assertion — the actual regression tripwire.
        $this->assertLessThan(
            self::BUILD_CEILING_SECONDS,
            $elapsed,
            sprintf(
                'CodeGraphAdjacencyIndex::fromEdges() took %.4fs for %d edges — over the %.1fs '
                .'catastrophic-regression ceiling. Did a build step go super-linear?',
                $elapsed,
                self::EDGE_COUNT,
                self::BUILD_CEILING_SECONDS
            )
        );

        // Correctness guard: every one of the 10k nodes is a source, so all are admitted.
        $this->assertSame(self::NODE_COUNT, $index->count(), 'all distinct nodes must be admitted');
    }

    /**
     * A batch of NODE_COUNT neighbors() lookups must complete under a generous ceiling,
     * proving per-lookup cost is O(1)-ish (a map read) and not O(E). Build is done OUTSIDE
     * the timed window so only the lookups are measured.
     */
    public function test_neighbors_batch_lookups_are_constant_time_under_budget(): void
    {
        config()->set('atlas.code_graph.max_adjacency_nodes', CodeGraphAdjacencyIndex::DEFAULT_MAX_NODES);

        $index = CodeGraphAdjacencyIndex::fromEdges($this->deterministicEdges());

        // Sink any reads so the optimizer/JIT cannot elide the loop, and to prove the
        // lookups actually return data (a no-op fast path would be a false pass).
        $checksum = 0;

        $start = microtime(true);
        for ($i = 0; $i < self::NODE_COUNT; $i++) {
            $checksum += count($index->neighbors('n'.$i));
        }
        $elapsed = microtime(true) - $start;

        $this->assertLessThan(
            self::NEIGHBORS_BATCH_CEILING_SECONDS,
            $elapsed,
            sprintf(
                '%d neighbors() lookups took %.4fs — over the %.1fs ceiling. A per-lookup '
                .'O(E) regression (re-walking the edge set) is the likely cause.',
                self::NODE_COUNT,
                $elapsed,
                self::NEIGHBORS_BATCH_CEILING_SECONDS
            )
        );

        // Every node is a source in the fixture, so every lookup returns >= 1 neighbor;
        // the batch therefore did real work (checksum strictly positive).
        $this->assertGreaterThan(0, $checksum, 'lookups returned no neighbors — fixture/path broken');
    }

    /**
     * A batch of incoming() (reverse-adjacency) lookups must ALSO stay under the same
     * O(1)-ish ceiling — the reverse map is the symmetric hot path used by blast-radius
     * and impact queries, so it gets its own tripwire.
     */
    public function test_incoming_batch_lookups_are_constant_time_under_budget(): void
    {
        config()->set('atlas.code_graph.max_adjacency_nodes', CodeGraphAdjacencyIndex::DEFAULT_MAX_NODES);

        $index = CodeGraphAdjacencyIndex::fromEdges($this->deterministicEdges());

        $checksum = 0;

        $start = microtime(true);
        for ($i = 0; $i < self::NODE_COUNT; $i++) {
            $checksum += count($index->incoming('n'.$i));
        }
        $elapsed = microtime(true) - $start;

        $this->assertLessThan(
            self::NEIGHBORS_BATCH_CEILING_SECONDS,
            $elapsed,
            sprintf(
                '%d incoming() lookups took %.4fs — over the %.1fs ceiling (reverse-map '
                .'O(E) regression?).',
                self::NODE_COUNT,
                $elapsed,
                self::NEIGHBORS_BATCH_CEILING_SECONDS
            )
        );

        $this->assertGreaterThan(0, $checksum, 'reverse lookups returned nothing — fixture/path broken');
    }

    /**
     * The DEFAULT_MAX_NODES ceiling is honored: with the cap set BELOW the fixture's
     * distinct-node count, the index admits exactly the cap and no more — proving the
     * memory bound a pathological edge dump relies on still bites at scale. (Not a timing
     * test; the bound is the regression surface here.)
     */
    public function test_node_ceiling_is_honored_at_scale(): void
    {
        $cap = 500; // well below NODE_COUNT (10000)
        config()->set('atlas.code_graph.max_adjacency_nodes', $cap);

        $index = CodeGraphAdjacencyIndex::fromEdges($this->deterministicEdges());

        $this->assertSame(
            $cap,
            $index->count(),
            sprintf('node ceiling (%d) must cap distinct nodes; got %d', $cap, $index->count())
        );

        // The literal default is also a contract: a config-free index uses 200k.
        $this->assertSame(200000, CodeGraphAdjacencyIndex::DEFAULT_MAX_NODES);
    }

    /**
     * The context-pack assembler must pack a large ranked candidate set (NODE_COUNT
     * nodes) under a token budget in a single in-order pass, well under a generous
     * ceiling — a quadratic regression in the packer would blow this. Builds the
     * candidate list OUTSIDE the timed window.
     */
    public function test_context_pack_assembler_packs_large_candidate_set_under_budget(): void
    {
        $assembler = new CodeGraphContextPackAssembler();

        // Deterministic ranked candidates: fixed 10-token cost each, ids n0..n{N-1}.
        $perNodeTokens = 10;
        $candidates = [];
        for ($i = 0; $i < self::NODE_COUNT; $i++) {
            $candidates[] = ['id' => 'n'.$i, 'tokens' => $perNodeTokens];
        }

        // Budget that fits exactly half the candidates, so the packer does real
        // inclusion AND exclusion work (a clean ranked prefix of 5000 nodes).
        $fit = (int) (self::NODE_COUNT / 2);
        $budget = $fit * $perNodeTokens;

        $start = microtime(true);
        $pack = $assembler->assemble($candidates, $budget);
        $elapsed = microtime(true) - $start;

        $this->assertLessThan(
            self::PACK_CEILING_SECONDS,
            $elapsed,
            sprintf(
                'CodeGraphContextPackAssembler::assemble() took %.4fs for %d candidates — '
                .'over the %.1fs ceiling. A super-linear packing regression is likely.',
                $elapsed,
                self::NODE_COUNT,
                self::PACK_CEILING_SECONDS
            )
        );

        // Correctness guard: exactly the rank-ordered prefix that fits, and the
        // estimate never exceeds the budget.
        $this->assertSame($fit, $pack['count'], 'packer must include exactly the prefix that fits the budget');
        $this->assertSame($budget, $pack['estimated_tokens'], 'estimate must equal the budget when it fills exactly');
        $this->assertTrue($pack['truncated'], 'the second half was excluded, so the pack is truncated');
    }
}
