<?php

namespace App\Services\Ai\Kernel\Evidence;

enum LedgerEventType: string
{
    case EnvelopeCreated = 'ENVELOPE_CREATED';
    case InputNormalized = 'INPUT_NORMALIZED';
    case IntentClassified = 'INTENT_CLASSIFIED';
    case DomainResolved = 'DOMAIN_RESOLVED';
    case FlowResolved = 'FLOW_RESOLVED';
    case ProfileResolved = 'PROFILE_RESOLVED';
    case PolicyCompiled = 'POLICY_COMPILED';
    case ContextComposed = 'CONTEXT_COMPOSED';
    case ContextInjected = 'CONTEXT_INJECTED';
    case DecisionDrafted = 'DECISION_DRAFTED';
    case DecisionIssued = 'DECISION_ISSUED';
    case DecisionConsumed = 'DECISION_CONSUMED';
    case DecisionExpired = 'DECISION_EXPIRED';
    case KernelPipelineAccepted = 'KERNEL_PIPELINE_ACCEPTED';
    case KernelPipelineRejected = 'KERNEL_PIPELINE_REJECTED';
    case OrchestratorSelected = 'ORCHESTRATOR_SELECTED';
    case ExecutionStarted = 'EXECUTION_STARTED';
    case ProviderCalled = 'PROVIDER_CALLED';
    case ProviderReturned = 'PROVIDER_RETURNED';
    case ProviderFallback = 'PROVIDER_FALLBACK';
    case ToolPlanned = 'TOOL_PLANNED';
    case ToolApproved = 'TOOL_APPROVED';
    case ToolInvoked = 'TOOL_INVOKED';
    case ToolReturned = 'TOOL_RETURNED';
    case ToolNormalized = 'TOOL_NORMALIZED';
    case ToolEvidenceRecorded = 'TOOL_EVIDENCE_RECORDED';
    case GateEvaluated = 'GATE_EVALUATED';
    case GatePassed = 'GATE_PASSED';
    case GateBlocked = 'GATE_BLOCKED';
    case RepairInitiated = 'REPAIR_INITIATED';
    case RepairCompleted = 'REPAIR_COMPLETED';
    case EscalationRequested = 'ESCALATION_REQUESTED';
    case EvidencePacked = 'EVIDENCE_PACKED';
    case LearningProposed = 'LEARNING_PROPOSED';
    case InboxActionRecorded = 'INBOX_ACTION_RECORDED';
    case SelfImprovementScheduleObserved = 'SELF_IMPROVEMENT_SCHEDULE_OBSERVED';
    case MemoryDeltaAccepted = 'MEMORY_DELTA_ACCEPTED';
    case SloObserved = 'SLO_OBSERVED';
    case VoiceSessionStarted = 'VOICE_SESSION_STARTED';
    case VoiceWakeWordDetected = 'VOICE_WAKE_WORD_DETECTED';
    case VoiceTurnAudioReceived = 'VOICE_TURN_AUDIO_RECEIVED';
    case VoiceTurnTranscribed = 'VOICE_TURN_TRANSCRIBED';
    case VoiceTurnDecided = 'VOICE_TURN_DECIDED';
    case VoiceTurnSynthesized = 'VOICE_TURN_SYNTHESIZED';
    case VoiceTurnPlayed = 'VOICE_TURN_PLAYED';
    case VoiceTurnInterrupted = 'VOICE_TURN_INTERRUPTED';
    case VoiceRuntimeFailed = 'VOICE_RUNTIME_FAILED';
    case VoiceEclipseTriggered = 'VOICE_ECLIPSE_TRIGGERED';
    case VoiceEclipseLifted = 'VOICE_ECLIPSE_LIFTED';
    case VoiceSessionEnded = 'VOICE_SESSION_ENDED';
    case VoiceProviderHealthDegraded = 'VOICE_PROVIDER_HEALTH_DEGRADED';
    case DreyfusLevelDeltaRecorded = 'DREYFUS_LEVEL_DELTA_RECORDED';
    case DreyfusPedagogyModeResolved = 'DREYFUS_PEDAGOGY_MODE_RESOLVED';
    case DreyfusDisputeOpened = 'DREYFUS_DISPUTE_OPENED';
    case DreyfusDisputeResolved = 'DREYFUS_DISPUTE_RESOLVED';
    case WorkedExampleDelivered = 'WORKED_EXAMPLE_DELIVERED';
    case WorkedExampleFadingProgressed = 'WORKED_EXAMPLE_FADING_PROGRESSED';
    case WorkedExampleAuthored = 'WORKED_EXAMPLE_AUTHORED';
    case WorkedExampleDeprecated = 'WORKED_EXAMPLE_DEPRECATED';
    case OperationCompleted = 'OPERATION_COMPLETED';
    case OperationFailed = 'OPERATION_FAILED';
    case OperationBlocked = 'OPERATION_BLOCKED';
    case OperationNeedsReview = 'OPERATION_NEEDS_REVIEW';
}
