<?php

declare(strict_types=1);

namespace App\Services\Ai\SelfConstruction\Readiness\HubDelegators;

use App\Services\Ai\SelfConstruction\Readiness\CertificationWorkbenchEvaluator;
use BadMethodCallException;

/**
 * Workbench certify projections as a method-name map (full-pass density).
 *
 * Formerly ~1985 LOC of near-identical public methods. Mother dispatches via
 * `$service->{$method}($options)` which resolves through __call.
 *
 * @phpstan-type WorkbenchStage 'contract'|'preflight'|'implementation_packet'
 */
trait CertificationWorkbenchEvaluatorDelegators
{
    /**
     * @var array<string, array{0: string, 1: string}>
     */
    private const CERTIFICATION_WORKBENCH_METHODS = [
        'agentControlPlaneCertificationBaselineContract' => ['certification_baseline', 'contract'],
        'agentControlPlaneCertificationBaselinePreflight' => ['certification_baseline', 'preflight'],
        'agentControlPlaneCertificationBaselineImplementationPacket' => ['certification_baseline', 'implementation_packet'],
        'agentControlPlaneCertificationScenarioSimulatorContract' => ['certification_scenario_simulator', 'contract'],
        'agentControlPlaneCertificationScenarioSimulatorPreflight' => ['certification_scenario_simulator', 'preflight'],
        'agentControlPlaneCertificationScenarioSimulatorImplementationPacket' => ['certification_scenario_simulator', 'implementation_packet'],
        'agentControlPlaneReleaseDossierContract' => ['release_dossier', 'contract'],
        'agentControlPlaneReleaseDossierPreflight' => ['release_dossier', 'preflight'],
        'agentControlPlaneReleaseDossierImplementationPacket' => ['release_dossier', 'implementation_packet'],
        'agentControlPlaneCertificationMutationGuardContract' => ['certification_mutation_guard', 'contract'],
        'agentControlPlaneCertificationMutationGuardPreflight' => ['certification_mutation_guard', 'preflight'],
        'agentControlPlaneCertificationMutationGuardImplementationPacket' => ['certification_mutation_guard', 'implementation_packet'],
        'agentControlPlaneCertificationEvidenceQueryContract' => ['certification_evidence_query', 'contract'],
        'agentControlPlaneCertificationEvidenceQueryPreflight' => ['certification_evidence_query', 'preflight'],
        'agentControlPlaneCertificationEvidenceQueryImplementationPacket' => ['certification_evidence_query', 'implementation_packet'],
        'agentControlPlaneCertificationScenarioCorpusContract' => ['certification_scenario_corpus', 'contract'],
        'agentControlPlaneCertificationScenarioCorpusPreflight' => ['certification_scenario_corpus', 'preflight'],
        'agentControlPlaneCertificationScenarioCorpusImplementationPacket' => ['certification_scenario_corpus', 'implementation_packet'],
        'agentControlPlaneCertificationFuzzHarnessContract' => ['certification_fuzz_harness', 'contract'],
        'agentControlPlaneCertificationFuzzHarnessPreflight' => ['certification_fuzz_harness', 'preflight'],
        'agentControlPlaneCertificationFuzzHarnessImplementationPacket' => ['certification_fuzz_harness', 'implementation_packet'],
        'agentControlPlaneMultiSnapshotComparisonContract' => ['multi_snapshot_comparison', 'contract'],
        'agentControlPlaneMultiSnapshotComparisonPreflight' => ['multi_snapshot_comparison', 'preflight'],
        'agentControlPlaneMultiSnapshotComparisonImplementationPacket' => ['multi_snapshot_comparison', 'implementation_packet'],
        'agentControlPlaneReleaseDossierExporterContract' => ['release_dossier_exporter', 'contract'],
        'agentControlPlaneReleaseDossierExporterPreflight' => ['release_dossier_exporter', 'preflight'],
        'agentControlPlaneReleaseDossierExporterImplementationPacket' => ['release_dossier_exporter', 'implementation_packet'],
        'agentControlPlaneCertificationCoverageReportContract' => ['certification_coverage_report', 'contract'],
        'agentControlPlaneCertificationCoverageReportPreflight' => ['certification_coverage_report', 'preflight'],
        'agentControlPlaneCertificationCoverageReportImplementationPacket' => ['certification_coverage_report', 'implementation_packet'],
        'agentControlPlaneCertificationStatusBatchContract' => ['certification_status_batch', 'contract'],
        'agentControlPlaneCertificationStatusBatchPreflight' => ['certification_status_batch', 'preflight'],
        'agentControlPlaneCertificationStatusBatchImplementationPacket' => ['certification_status_batch', 'implementation_packet'],
        'atlasSelfConstructionOsCompletionAuditContract' => ['atlas_self_construction_os_completion_audit', 'contract'],
        'atlasSelfConstructionOsCompletionAuditPreflight' => ['atlas_self_construction_os_completion_audit', 'preflight'],
        'atlasSelfConstructionOsCompletionAuditImplementationPacket' => ['atlas_self_construction_os_completion_audit', 'implementation_packet'],
        'atlasSelfConstructionOsCompletionOperatorActionPacketContract' => ['atlas_self_construction_os_completion_operator_action_packet', 'contract'],
        'atlasSelfConstructionOsCompletionOperatorActionPacketPreflight' => ['atlas_self_construction_os_completion_operator_action_packet', 'preflight'],
        'atlasSelfConstructionOsCompletionOperatorActionPacketImplementationPacket' => ['atlas_self_construction_os_completion_operator_action_packet', 'implementation_packet'],
        'atlasSelfConstructionFinalEvidenceBundleContract' => ['atlas_self_construction_final_evidence_bundle', 'contract'],
        'atlasSelfConstructionFinalEvidenceBundlePreflight' => ['atlas_self_construction_final_evidence_bundle', 'preflight'],
        'atlasSelfConstructionFinalEvidenceBundleImplementationPacket' => ['atlas_self_construction_final_evidence_bundle', 'implementation_packet'],
        'atlasSelfConstructionCompletionAuditBlockerExplainerContract' => ['atlas_self_construction_completion_audit_blocker_explainer', 'contract'],
        'atlasSelfConstructionCompletionAuditBlockerExplainerPreflight' => ['atlas_self_construction_completion_audit_blocker_explainer', 'preflight'],
        'atlasSelfConstructionCompletionAuditBlockerExplainerImplementationPacket' => ['atlas_self_construction_completion_audit_blocker_explainer', 'implementation_packet'],
        'atlasSelfConstructionCompletionEvidenceSubmissionPreflightContract' => ['atlas_self_construction_completion_evidence_submission_preflight', 'contract'],
        'atlasSelfConstructionCompletionEvidenceSubmissionPreflightPreflight' => ['atlas_self_construction_completion_evidence_submission_preflight', 'preflight'],
        'atlasSelfConstructionCompletionEvidenceSubmissionPreflightImplementationPacket' => ['atlas_self_construction_completion_evidence_submission_preflight', 'implementation_packet'],
        'atlasSelfConstructionOsHandoffContract' => ['atlas_self_construction_os_handoff', 'contract'],
        'atlasSelfConstructionOsHandoffPreflight' => ['atlas_self_construction_os_handoff', 'preflight'],
        'atlasSelfConstructionOsHandoffImplementationPacket' => ['atlas_self_construction_os_handoff', 'implementation_packet'],
        'atlasSelfConstructionCompletionEvidenceHashComposerContract' => ['atlas_self_construction_completion_evidence_hash_composer', 'contract'],
        'atlasSelfConstructionCompletionEvidenceHashComposerPreflight' => ['atlas_self_construction_completion_evidence_hash_composer', 'preflight'],
        'atlasSelfConstructionCompletionEvidenceHashComposerImplementationPacket' => ['atlas_self_construction_completion_evidence_hash_composer', 'implementation_packet'],
        'atlasSelfConstructionOperatorEvidenceDraftHashFinalizerContract' => ['atlas_self_construction_operator_evidence_draft_hash_finalizer', 'contract'],
        'atlasSelfConstructionOperatorEvidenceDraftHashFinalizerPreflight' => ['atlas_self_construction_operator_evidence_draft_hash_finalizer', 'preflight'],
        'atlasSelfConstructionOperatorEvidenceDraftHashFinalizerImplementationPacket' => ['atlas_self_construction_operator_evidence_draft_hash_finalizer', 'implementation_packet'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspacePublisherContract' => ['atlas_self_construction_operator_evidence_draft_workspace_publisher', 'contract'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspacePublisherPreflight' => ['atlas_self_construction_operator_evidence_draft_workspace_publisher', 'preflight'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspacePublisherImplementationPacket' => ['atlas_self_construction_operator_evidence_draft_workspace_publisher', 'implementation_packet'],
        'atlasSelfConstructionFinalOperatorEvidenceClosureCorridorContract' => ['atlas_self_construction_final_operator_evidence_closure_corridor', 'contract'],
        'atlasSelfConstructionFinalOperatorEvidenceClosureCorridorPreflight' => ['atlas_self_construction_final_operator_evidence_closure_corridor', 'preflight'],
        'atlasSelfConstructionFinalOperatorEvidenceClosureCorridorImplementationPacket' => ['atlas_self_construction_final_operator_evidence_closure_corridor', 'implementation_packet'],
        'atlasSelfConstructionOperatorEvidenceArtifactTemplatePackContract' => ['atlas_self_construction_operator_evidence_artifact_template_pack', 'contract'],
        'atlasSelfConstructionOperatorEvidenceArtifactTemplatePackPreflight' => ['atlas_self_construction_operator_evidence_artifact_template_pack', 'preflight'],
        'atlasSelfConstructionOperatorEvidenceArtifactTemplatePackImplementationPacket' => ['atlas_self_construction_operator_evidence_artifact_template_pack', 'implementation_packet'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspaceInspectorContract' => ['atlas_self_construction_operator_evidence_draft_workspace_inspector', 'contract'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspaceInspectorPreflight' => ['atlas_self_construction_operator_evidence_draft_workspace_inspector', 'preflight'],
        'atlasSelfConstructionOperatorEvidenceDraftWorkspaceInspectorImplementationPacket' => ['atlas_self_construction_operator_evidence_draft_workspace_inspector', 'implementation_packet'],
        'atlasSelfConstructionOperatorEvidenceSubmissionReadinessContract' => ['atlas_self_construction_operator_evidence_submission_readiness', 'contract'],
        'atlasSelfConstructionOperatorEvidenceSubmissionReadinessPreflight' => ['atlas_self_construction_operator_evidence_submission_readiness', 'preflight'],
        'atlasSelfConstructionOperatorEvidenceSubmissionReadinessImplementationPacket' => ['atlas_self_construction_operator_evidence_submission_readiness', 'implementation_packet'],
        'atlasSelfConstructionFinalCompletionHumanGateContract' => ['atlas_self_construction_final_completion_human_gate', 'contract'],
        'atlasSelfConstructionFinalCompletionHumanGatePreflight' => ['atlas_self_construction_final_completion_human_gate', 'preflight'],
        'atlasSelfConstructionFinalCompletionHumanGateImplementationPacket' => ['atlas_self_construction_final_completion_human_gate', 'implementation_packet'],
        'atlasSelfConstructionFinalCompletionDossierExporterContract' => ['atlas_self_construction_final_completion_dossier_exporter', 'contract'],
        'atlasSelfConstructionFinalCompletionDossierExporterPreflight' => ['atlas_self_construction_final_completion_dossier_exporter', 'preflight'],
        'atlasSelfConstructionFinalCompletionDossierExporterImplementationPacket' => ['atlas_self_construction_final_completion_dossier_exporter', 'implementation_packet'],
        'atlasSelfConstructionFinalCompletionReadinessGateContract' => ['atlas_self_construction_final_completion_readiness_gate', 'contract'],
        'atlasSelfConstructionFinalCompletionReadinessGatePreflight' => ['atlas_self_construction_final_completion_readiness_gate', 'preflight'],
        'atlasSelfConstructionFinalCompletionReadinessGateImplementationPacket' => ['atlas_self_construction_final_completion_readiness_gate', 'implementation_packet'],
        'atlasSelfProgrammingOsTransitionReadinessContract' => ['atlas_self_programming_os_transition_readiness', 'contract'],
        'atlasSelfProgrammingOsTransitionReadinessPreflight' => ['atlas_self_programming_os_transition_readiness', 'preflight'],
        'atlasSelfProgrammingOsTransitionReadinessImplementationPacket' => ['atlas_self_programming_os_transition_readiness', 'implementation_packet'],
        'atlasSelfProgrammingSafetyContractCertificationContract' => ['atlas_self_programming_safety_contract_certification', 'contract'],
        'atlasSelfProgrammingSafetyContractCertificationPreflight' => ['atlas_self_programming_safety_contract_certification', 'preflight'],
        'atlasSelfProgrammingSafetyContractCertificationImplementationPacket' => ['atlas_self_programming_safety_contract_certification', 'implementation_packet'],
        'atlasSelfConstructionCompletionFinalizationGateContract' => ['atlas_self_construction_completion_finalization_gate', 'contract'],
        'atlasSelfConstructionCompletionFinalizationGatePreflight' => ['atlas_self_construction_completion_finalization_gate', 'preflight'],
        'atlasSelfConstructionCompletionFinalizationGateImplementationPacket' => ['atlas_self_construction_completion_finalization_gate', 'implementation_packet'],
        'agentControlPlaneRuntimeEvidenceJournalContract' => ['runtime_evidence_journal', 'contract'],
        'agentControlPlaneRuntimeEvidenceJournalPreflight' => ['runtime_evidence_journal', 'preflight'],
        'agentControlPlaneRuntimeEvidenceJournalImplementationPacket' => ['runtime_evidence_journal', 'implementation_packet'],
        'agentControlPlaneExecutionWorkspaceRuntimeContract' => ['execution_workspace_runtime', 'contract'],
        'agentControlPlaneExecutionWorkspaceRuntimePreflight' => ['execution_workspace_runtime', 'preflight'],
        'agentControlPlaneExecutionWorkspaceRuntimeImplementationPacket' => ['execution_workspace_runtime', 'implementation_packet'],
        'agentControlPlaneGovernanceApprovalRuntimeContract' => ['governance_approval_runtime', 'contract'],
        'agentControlPlaneGovernanceApprovalRuntimePreflight' => ['governance_approval_runtime', 'preflight'],
        'agentControlPlaneGovernanceApprovalRuntimeImplementationPacket' => ['governance_approval_runtime', 'implementation_packet'],
        'agentControlPlaneAutomaticCostImportRuntimeContract' => ['automatic_cost_import_runtime', 'contract'],
        'agentControlPlaneAutomaticCostImportRuntimePreflight' => ['automatic_cost_import_runtime', 'preflight'],
        'agentControlPlaneAutomaticCostImportRuntimeImplementationPacket' => ['automatic_cost_import_runtime', 'implementation_packet'],
        'agentControlPlaneAutomaticWorkProductCollectionRuntimeContract' => ['automatic_work_product_collection_runtime', 'contract'],
        'agentControlPlaneAutomaticWorkProductCollectionRuntimePreflight' => ['automatic_work_product_collection_runtime', 'preflight'],
        'agentControlPlaneAutomaticWorkProductCollectionRuntimeImplementationPacket' => ['automatic_work_product_collection_runtime', 'implementation_packet'],
        'agentControlPlaneAdapterExecutionRuntimeBoundaryContract' => ['adapter_execution_runtime_boundary', 'contract'],
        'agentControlPlaneAdapterExecutionRuntimeBoundaryPreflight' => ['adapter_execution_runtime_boundary', 'preflight'],
        'agentControlPlaneAdapterExecutionRuntimeBoundaryImplementationPacket' => ['adapter_execution_runtime_boundary', 'implementation_packet'],
        'agentControlPlaneDispatchPlannerRuntimeContract' => ['dispatch_planner_runtime', 'contract'],
        'agentControlPlaneDispatchPlannerRuntimePreflight' => ['dispatch_planner_runtime', 'preflight'],
        'agentControlPlaneDispatchPlannerRuntimeImplementationPacket' => ['dispatch_planner_runtime', 'implementation_packet'],
        'agentControlPlaneValidationGateRuntimeContract' => ['validation_gate_runtime', 'contract'],
        'agentControlPlaneValidationGateRuntimePreflight' => ['validation_gate_runtime', 'preflight'],
        'agentControlPlaneValidationGateRuntimeImplementationPacket' => ['validation_gate_runtime', 'implementation_packet'],
        'agentControlPlaneMergeReviewRuntimeContract' => ['merge_review_runtime', 'contract'],
        'agentControlPlaneMergeReviewRuntimePreflight' => ['merge_review_runtime', 'preflight'],
        'agentControlPlaneMergeReviewRuntimeImplementationPacket' => ['merge_review_runtime', 'implementation_packet'],
        'agentControlPlaneTaskPacketBuilderContract' => ['task_packet_builder', 'contract'],
        'agentControlPlaneTaskPacketBuilderPreflight' => ['task_packet_builder', 'preflight'],
        'agentControlPlaneTaskPacketBuilderImplementationPacket' => ['task_packet_builder', 'implementation_packet'],
        'agentControlPlaneClaimLeaseSimulatorContract' => ['claim_lease_simulator', 'contract'],
        'agentControlPlaneClaimLeaseSimulatorPreflight' => ['claim_lease_simulator', 'preflight'],
        'agentControlPlaneClaimLeaseSimulatorImplementationPacket' => ['claim_lease_simulator', 'implementation_packet'],
        'agentControlPlaneScopeLockPlannerContract' => ['scope_lock_planner', 'contract'],
        'agentControlPlaneScopeLockPlannerPreflight' => ['scope_lock_planner', 'preflight'],
        'agentControlPlaneScopeLockPlannerImplementationPacket' => ['scope_lock_planner', 'implementation_packet'],
        'agentControlPlaneEvidenceLedgerDryRunContract' => ['evidence_ledger_dry_run', 'contract'],
        'agentControlPlaneEvidenceLedgerDryRunPreflight' => ['evidence_ledger_dry_run', 'preflight'],
        'agentControlPlaneEvidenceLedgerDryRunImplementationPacket' => ['evidence_ledger_dry_run', 'implementation_packet'],
        'agentControlPlaneContinuationSummaryBuilderContract' => ['continuation_summary_builder', 'contract'],
        'agentControlPlaneContinuationSummaryBuilderPreflight' => ['continuation_summary_builder', 'preflight'],
        'agentControlPlaneContinuationSummaryBuilderImplementationPacket' => ['continuation_summary_builder', 'implementation_packet'],
        'agentControlPlaneWorkProductManifestPlannerContract' => ['work_product_manifest_planner', 'contract'],
        'agentControlPlaneWorkProductManifestPlannerPreflight' => ['work_product_manifest_planner', 'preflight'],
        'agentControlPlaneWorkProductManifestPlannerImplementationPacket' => ['work_product_manifest_planner', 'implementation_packet'],
        'agentControlPlaneCostImportDryRunContract' => ['cost_import_dry_run', 'contract'],
        'agentControlPlaneCostImportDryRunPreflight' => ['cost_import_dry_run', 'preflight'],
        'agentControlPlaneCostImportDryRunImplementationPacket' => ['cost_import_dry_run', 'implementation_packet'],
        'agentControlPlaneMultiAgentParallelismPlannerContract' => ['multi_agent_parallelism_planner', 'contract'],
        'agentControlPlaneMultiAgentParallelismPlannerPreflight' => ['multi_agent_parallelism_planner', 'preflight'],
        'agentControlPlaneMultiAgentParallelismPlannerImplementationPacket' => ['multi_agent_parallelism_planner', 'implementation_packet'],
        'agentControlPlaneRuntimePilotOrchestratorContract' => ['runtime_pilot_orchestrator', 'contract'],
        'agentControlPlaneRuntimePilotOrchestratorPreflight' => ['runtime_pilot_orchestrator', 'preflight'],
        'agentControlPlaneRuntimePilotOrchestratorImplementationPacket' => ['runtime_pilot_orchestrator', 'implementation_packet'],
        'agentControlPlaneRuntimePilotCertificationContract' => ['runtime_pilot_certification', 'contract'],
        'agentControlPlaneRuntimePilotCertificationPreflight' => ['runtime_pilot_certification', 'preflight'],
        'agentControlPlaneRuntimePilotCertificationImplementationPacket' => ['runtime_pilot_certification', 'implementation_packet'],
        'agentControlPlaneTaskPacketQueueContract' => ['task_packet_queue', 'contract'],
        'agentControlPlaneTaskPacketQueuePreflight' => ['task_packet_queue', 'preflight'],
        'agentControlPlaneTaskPacketQueueImplementationPacket' => ['task_packet_queue', 'implementation_packet'],
        'agentControlPlaneClaimLeaseRuntimeContract' => ['claim_lease_runtime', 'contract'],
        'agentControlPlaneClaimLeaseRuntimePreflight' => ['claim_lease_runtime', 'preflight'],
        'agentControlPlaneClaimLeaseRuntimeImplementationPacket' => ['claim_lease_runtime', 'implementation_packet'],
        'agentControlPlaneTaskLeaseRecoveryContract' => ['task_lease_recovery', 'contract'],
        'agentControlPlaneTaskLeaseRecoveryPreflight' => ['task_lease_recovery', 'preflight'],
        'agentControlPlaneTaskLeaseRecoveryImplementationPacket' => ['task_lease_recovery', 'implementation_packet'],
        'agentControlPlaneScopeLockRuntimeValidatorContract' => ['scope_lock_runtime_validator', 'contract'],
        'agentControlPlaneScopeLockRuntimeValidatorPreflight' => ['scope_lock_runtime_validator', 'preflight'],
        'agentControlPlaneScopeLockRuntimeValidatorImplementationPacket' => ['scope_lock_runtime_validator', 'implementation_packet'],
        'agentControlPlaneTaskQueueOrchestratorContract' => ['task_queue_orchestrator', 'contract'],
        'agentControlPlaneTaskQueueOrchestratorPreflight' => ['task_queue_orchestrator', 'preflight'],
        'agentControlPlaneTaskQueueOrchestratorImplementationPacket' => ['task_queue_orchestrator', 'implementation_packet'],
        'agentControlPlaneTaskAutoReplenishmentContract' => ['task_auto_replenishment', 'contract'],
        'agentControlPlaneTaskAutoReplenishmentPreflight' => ['task_auto_replenishment', 'preflight'],
        'agentControlPlaneTaskAutoReplenishmentImplementationPacket' => ['task_auto_replenishment', 'implementation_packet'],
        'agentControlPlaneWorkerTaskEligibilityCertificationContract' => ['worker_task_eligibility_certification', 'contract'],
        'agentControlPlaneWorkerTaskEligibilityCertificationPreflight' => ['worker_task_eligibility_certification', 'preflight'],
        'agentControlPlaneWorkerTaskEligibilityCertificationImplementationPacket' => ['worker_task_eligibility_certification', 'implementation_packet'],
        'agentControlPlaneTerminalLoopHealthDigestContract' => ['terminal_loop_health_digest', 'contract'],
        'agentControlPlaneTerminalLoopHealthDigestPreflight' => ['terminal_loop_health_digest', 'preflight'],
        'agentControlPlaneTerminalLoopHealthDigestImplementationPacket' => ['terminal_loop_health_digest', 'implementation_packet'],
        'agentControlPlaneTerminalLoopOperationalProofContract' => ['terminal_loop_operational_proof', 'contract'],
        'agentControlPlaneTerminalLoopOperationalProofPreflight' => ['terminal_loop_operational_proof', 'preflight'],
        'agentControlPlaneTerminalLoopOperationalProofImplementationPacket' => ['terminal_loop_operational_proof', 'implementation_packet'],
        'agentControlPlaneTerminalWorkerBootstrapContract' => ['terminal_worker_bootstrap', 'contract'],
        'agentControlPlaneTerminalWorkerBootstrapPreflight' => ['terminal_worker_bootstrap', 'preflight'],
        'agentControlPlaneTerminalWorkerBootstrapImplementationPacket' => ['terminal_worker_bootstrap', 'implementation_packet'],
        'atlasSelfConstructionOsRuntimeGapMatrixAuditContract' => ['runtime_gap_matrix_audit', 'contract'],
        'atlasSelfConstructionOsRuntimeGapMatrixAuditPreflight' => ['runtime_gap_matrix_audit', 'preflight'],
        'atlasSelfConstructionOsRuntimeGapMatrixAuditImplementationPacket' => ['runtime_gap_matrix_audit', 'implementation_packet'],
        'agentControlPlaneTaskQueueLeaseCertificationContract' => ['task_queue_lease_certification', 'contract'],
        'agentControlPlaneTaskQueueLeaseCertificationPreflight' => ['task_queue_lease_certification', 'preflight'],
        'agentControlPlaneTaskQueueLeaseCertificationImplementationPacket' => ['task_queue_lease_certification', 'implementation_packet'],
        'agentControlPlaneMultiAgentLoopCertificationContract' => ['multi_agent_loop_certification', 'contract'],
        'agentControlPlaneMultiAgentLoopCertificationPreflight' => ['multi_agent_loop_certification', 'preflight'],
        'agentControlPlaneMultiAgentLoopCertificationImplementationPacket' => ['multi_agent_loop_certification', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryContract' => ['agent_runtime_registry', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryPreflight' => ['agent_runtime_registry', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryImplementationPacket' => ['agent_runtime_registry', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryHeartbeatContract' => ['agent_runtime_registry_heartbeat', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryHeartbeatPreflight' => ['agent_runtime_registry_heartbeat', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryHeartbeatImplementationPacket' => ['agent_runtime_registry_heartbeat', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryCapabilityCatalogContract' => ['agent_runtime_registry_capability_catalog', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryCapabilityCatalogPreflight' => ['agent_runtime_registry_capability_catalog', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryCapabilityCatalogImplementationPacket' => ['agent_runtime_registry_capability_catalog', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryAvailabilityContract' => ['agent_runtime_registry_availability', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryAvailabilityPreflight' => ['agent_runtime_registry_availability', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryAvailabilityImplementationPacket' => ['agent_runtime_registry_availability', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryTaskMatcherContract' => ['agent_runtime_registry_task_matcher', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryTaskMatcherPreflight' => ['agent_runtime_registry_task_matcher', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryTaskMatcherImplementationPacket' => ['agent_runtime_registry_task_matcher', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryLoadBalancingContract' => ['agent_runtime_registry_load_balancing', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryLoadBalancingPreflight' => ['agent_runtime_registry_load_balancing', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryLoadBalancingImplementationPacket' => ['agent_runtime_registry_load_balancing', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryQuarantineContract' => ['agent_runtime_registry_quarantine', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryQuarantinePreflight' => ['agent_runtime_registry_quarantine', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryQuarantineImplementationPacket' => ['agent_runtime_registry_quarantine', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryHandoffContract' => ['agent_runtime_registry_handoff', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryHandoffPreflight' => ['agent_runtime_registry_handoff', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryHandoffImplementationPacket' => ['agent_runtime_registry_handoff', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryOrchestratorContract' => ['agent_runtime_registry_orchestrator', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryOrchestratorPreflight' => ['agent_runtime_registry_orchestrator', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryOrchestratorImplementationPacket' => ['agent_runtime_registry_orchestrator', 'implementation_packet'],
        'agentControlPlaneAgentRuntimeRegistryCertificationContract' => ['agent_runtime_registry_certification', 'contract'],
        'agentControlPlaneAgentRuntimeRegistryCertificationPreflight' => ['agent_runtime_registry_certification', 'preflight'],
        'agentControlPlaneAgentRuntimeRegistryCertificationImplementationPacket' => ['agent_runtime_registry_certification', 'implementation_packet'],
        'agentControlPlaneOneShotWorkerPacketContract' => ['one_shot_worker_packet', 'contract'],
        'agentControlPlaneOneShotWorkerPacketPreflight' => ['one_shot_worker_packet', 'preflight'],
        'agentControlPlaneOneShotWorkerPacketImplementationPacket' => ['one_shot_worker_packet', 'implementation_packet'],
    ];

    /**
     * @param  array<int, mixed>  $arguments
     * @return array<string, mixed>
     */
    public function __call(string $name, array $arguments): mixed
    {
        if (! isset(self::CERTIFICATION_WORKBENCH_METHODS[$name])) {
            throw new BadMethodCallException(sprintf(
                '%s has no method %s (not a certification workbench projection).',
                static::class,
                $name,
            ));
        }

        [$key, $stage] = self::CERTIFICATION_WORKBENCH_METHODS[$name];

        return CertificationWorkbenchEvaluator::certify($key, $stage);
    }

    /**
     * @return list<string>
     */
    public static function certificationWorkbenchMethodNames(): array
    {
        return array_keys(self::CERTIFICATION_WORKBENCH_METHODS);
    }
}
