<?php

namespace App\Services\Ai\Kernel\Architecture;

final class AtlasApAgentWorkflowRegistry
{
    private const SCHEMA_VERSION = 'atlas.ap_agent_workflow_registry.v1';

    /**
     * @return array<string,mixed>
     */
    public function workflow(): array
    {
        $steps = $this->steps();

        return [
            'schema_version' => self::SCHEMA_VERSION,
            'status' => 'implemented',
            'mode' => 'read_only_workflow_registry',
            'authority' => 'ap_agent_workflow_registry_only_no_execution',
            'workflow_id' => 'ap_agent_documented_work_session',
            'step_count' => count($steps),
            'steps' => $steps,
            'terminal_statuses' => [
                'ready' => [
                    'ready_for_new_ap_work',
                    'ready_for_existing_ap_work',
                    'complete',
                    'accepted',
                    'ready_for_human_acceptance',
                    'accepted_by_human',
                    'ready_for_integrator_review',
                    'ready_for_manual_integration',
                    'manual_integration_reported',
                    'ready_for_final_human_closeout_review',
                    'closeout_accepted_by_human',
                    'closeout_acceptance_reported',
                    'ready_for_future_release_or_evidence_layer',
                    'ready_for_release_evidence_owner_review',
                    'release_evidence_candidate_ready_for_human_review',
                    'release_evidence_candidate_accepted_by_human',
                    'release_evidence_candidate_acceptance_reported',
                    'ready_for_future_release_or_ledger_execution_ap',
                    'ready_for_future_dry_run_review',
                    'dry_run_plan_accepted_by_human',
                    'dry_run_result_envelope_ready_for_human_review',
                    'dry_run_result_accepted_by_human',
                    'post_dry_run_handoff_ready_for_future_release_or_ledger_ap',
                    'consumer_readiness_ready_for_future_release_or_ledger_decision',
                    'consumer_readiness_accepted_by_human',
                    'consumer_readiness_acceptance_reported',
                    'ready_for_execution_authorization_decision',
                    'execution_authorization_approved_by_human',
                    'execution_authorization_approval_reported',
                    'execution_authorization_handoff_ready_for_future_execution_ap',
                    'ready_for_execution_implementation_review',
                    'execution_implementation_accepted_by_human',
                    'execution_implementation_acceptance_reported',
                    'ready_for_execution_activation_review',
                    'execution_activation_accepted_by_human',
                    'execution_activation_acceptance_reported',
                    'ready_for_runtime_execution_review',
                ],
                'blocked' => [
                    'blocked',
                    'blocked_by_documentation_repair',
                    'blocked_by_handoff',
                    'blocked_by_session_gate',
                    'blocked_by_validation_evidence_shape',
                    'blocked_by_trace_audit',
                    'blocked_by_completion_report',
                    'blocked_by_human_decision_contract',
                    'blocked_by_integrator_handoff',
                    'blocked_by_integrator_readiness',
                    'blocked_by_manual_integration_receipt',
                    'blocked_by_closeout_decision_contract',
                    'blocked_by_closeout_acceptance_receipt',
                    'blocked_by_release_evidence_preflight',
                    'blocked_by_release_evidence_handoff_packet',
                    'blocked_by_release_evidence_candidate_contract',
                    'blocked_by_candidate_decision_contract',
                    'blocked_by_candidate_decision_receipt',
                    'blocked_by_execution_readiness',
                    'blocked_by_dry_run_plan_contract',
                    'blocked_invalid_dry_run_review_decision',
                    'blocked_by_dry_run_review_contract',
                    'blocked_invalid_dry_run_result_shape',
                    'blocked_by_dry_run_result_envelope_contract',
                    'blocked_invalid_dry_run_result_review_decision',
                    'blocked_by_dry_run_result_review_contract',
                    'blocked_invalid_post_dry_run_handoff_shape',
                    'blocked_by_post_dry_run_handoff_packet',
                    'blocked_invalid_consumer_readiness_shape',
                    'blocked_by_consumer_readiness_contract',
                    'blocked_invalid_consumer_readiness_decision',
                    'blocked_by_consumer_readiness_decision_contract',
                    'blocked_by_consumer_readiness_decision_receipt',
                    'blocked_invalid_execution_authorization_preflight_shape',
                    'blocked_by_execution_authorization_preflight',
                    'blocked_invalid_execution_authorization_decision',
                    'blocked_by_execution_authorization_decision_contract',
                    'blocked_by_execution_authorization_decision_receipt',
                    'blocked_invalid_execution_authorization_handoff_shape',
                    'blocked_by_execution_authorization_handoff_packet',
                    'blocked_invalid_execution_implementation_preflight_shape',
                    'blocked_by_execution_implementation_preflight',
                    'blocked_invalid_execution_implementation_decision',
                    'blocked_by_execution_implementation_decision_contract',
                    'blocked_by_execution_implementation_decision_receipt',
                    'blocked_invalid_execution_activation_preflight_shape',
                    'blocked_by_execution_activation_preflight',
                    'blocked_invalid_execution_activation_decision',
                    'blocked_by_execution_activation_decision_contract',
                    'blocked_by_execution_activation_decision_receipt',
                    'blocked_invalid_runtime_execution_preflight_shape',
                ],
                'attention' => [
                    'attention',
                    'incomplete',
                    'requires_human_repair_review',
                    'changes_requested_by_human',
                    'return_to_agent_for_repair',
                    'integrator_review_incomplete',
                    'manual_integration_evidence_incomplete',
                    'final_audit_incomplete',
                    'closeout_changes_requested_by_human',
                    'closeout_returned_for_repair',
                    'release_evidence_preflight_incomplete',
                    'release_evidence_handoff_incomplete',
                    'release_evidence_candidate_incomplete',
                    'release_evidence_candidate_changes_requested_by_human',
                    'release_evidence_candidate_rejected_by_human',
                    'release_evidence_candidate_returned_for_repair',
                    'release_evidence_execution_readiness_incomplete',
                    'release_evidence_dry_run_plan_incomplete',
                    'dry_run_plan_changes_requested_by_human',
                    'dry_run_plan_rejected_by_human',
                    'dry_run_result_evidence_incomplete',
                    'dry_run_result_changes_requested_by_human',
                    'dry_run_result_rejected_by_human',
                    'post_dry_run_handoff_evidence_incomplete',
                    'consumer_readiness_evidence_incomplete',
                    'consumer_readiness_changes_requested_by_human',
                    'consumer_readiness_rejected_by_human',
                    'consumer_readiness_returned_for_repair',
                    'consumer_readiness_stopped_by_rejection',
                    'execution_authorization_preflight_incomplete',
                    'execution_authorization_changes_requested_by_human',
                    'execution_authorization_rejected_by_human',
                    'execution_authorization_returned_for_repair',
                    'execution_authorization_stopped_by_rejection',
                    'execution_authorization_handoff_evidence_incomplete',
                    'execution_implementation_preflight_incomplete',
                    'execution_implementation_changes_requested_by_human',
                    'execution_implementation_rejected_by_human',
                    'execution_implementation_returned_for_repair',
                    'execution_implementation_stopped_by_rejection',
                    'execution_activation_preflight_incomplete',
                    'execution_activation_changes_requested_by_human',
                    'execution_activation_rejected_by_human',
                    'execution_activation_returned_for_repair',
                    'execution_activation_stopped_by_rejection',
                    'runtime_execution_preflight_incomplete',
                ],
            ],
            'required_validation_commands' => [
                'focused_tests' => 'php artisan test <focused-test-files-or-filter>',
                'docs_health' => 'atlas engineering knowledge docs-health',
                'architecture_validate' => 'php artisan atlas:ai:architecture-validate --json',
                'architecture_readiness' => 'php artisan atlas:ai:architecture-readiness --json',
                'knowledge_sync' => 'atlas engineering knowledge sync --prune',
                'code_intelligence_index' => 'atlas engineering knowledge index-code --prune',
                'diff_check' => 'git diff --check',
            ],
            'handoff_summary' => [
                'start_with' => 'AtlasApAgentHandoffPacket',
                'repair_before_work' => 'AtlasApGovernanceRepairProposalContract',
                'gate_before_editing' => 'AtlasApAgentSessionGate',
                'validate_before_completion' => 'AtlasApValidationEvidenceContract',
                'finish_with' => 'AtlasApAgentCompletionReport',
                'audit_trace_with' => 'AtlasApAgentWorkflowTraceAudit',
                'review_with' => 'AtlasApAgentWorkflowHumanReviewPacket',
                'handoff_to_integrator_with' => 'AtlasApAgentWorkflowIntegratorHandoffPacket',
                'closeout_with' => 'AtlasApAgentWorkflowCloseoutAcceptanceReceipt',
                'review_dry_run_plan_with' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunReviewContract',
                'seal_dry_run_result_with' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunResultEnvelopeContract',
                'review_dry_run_result_with' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunResultReviewContract',
                'handoff_after_dry_run_with' => 'AtlasApAgentWorkflowReleaseEvidencePostDryRunHandoffPacket',
                'check_consumer_readiness_with' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessContract',
                'decide_consumer_readiness_with' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessDecisionContract',
                'receipt_consumer_readiness_decision_with' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessDecisionReceipt',
                'preflight_execution_authorization_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationPreflight',
                'decide_execution_authorization_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationDecisionContract',
                'receipt_execution_authorization_decision_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationDecisionReceipt',
                'handoff_execution_authorization_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationHandoffPacket',
                'preflight_execution_implementation_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationPreflight',
                'decide_execution_implementation_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationDecisionContract',
                'receipt_execution_implementation_decision_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationDecisionReceipt',
                'preflight_execution_activation_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationPreflight',
                'decide_execution_activation_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationDecisionContract',
                'receipt_execution_activation_decision_with' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationDecisionReceipt',
                'preflight_runtime_execution_with' => 'AtlasApAgentWorkflowReleaseEvidenceRuntimeExecutionPreflight',
            ],
            'post_completion_review_chain' => $this->postCompletionReviewChain(),
            'next_action' => 'use_workflow_registry_to_sequence_agent_ap_work_without_creating_parallel_flow',
            'guardrails' => [
                'writes_files' => false,
                'executes_commands' => false,
                'evaluates_runtime_state' => false,
                'creates_parallel_flow' => false,
                'replaces_handoff_packet' => false,
                'replaces_session_gate' => false,
                'replaces_validation_evidence_contract' => false,
                'replaces_completion_report' => false,
            ],
        ];
    }

    /**
     * @return array<int,array<string,mixed>>
     */
    private function steps(): array
    {
        return [
            [
                'order' => 1,
                'ap' => 'AP-200',
                'component' => 'AtlasApAgentHandoffPacket',
                'schema_version' => 'atlas.ap_agent_handoff_packet.v1',
                'purpose' => 'resolve_work_intake_target_context_and_initial_completion_checklist',
                'allowed_next_steps' => ['AP-201', 'AP-202'],
                'blocks_when' => ['intake_status_blocked', 'target_context_not_ready'],
            ],
            [
                'order' => 2,
                'ap' => 'AP-201',
                'component' => 'AtlasApGovernanceRepairProposalContract',
                'schema_version' => 'atlas.ap_governance_repair_proposal_contract.v1',
                'purpose' => 'turn_documentation_governance_findings_into_human_review_repair_proposals',
                'allowed_next_steps' => ['AP-202'],
                'blocks_when' => ['proposal_count_greater_than_zero'],
            ],
            [
                'order' => 3,
                'ap' => 'AP-202',
                'component' => 'AtlasApAgentSessionGate',
                'schema_version' => 'atlas.ap_agent_session_gate.v1',
                'purpose' => 'decide_whether_agent_session_can_start',
                'allowed_next_steps' => ['AP-205'],
                'blocks_when' => ['documentation_repair_pending', 'handoff_blocked'],
            ],
            [
                'order' => 4,
                'ap' => 'AP-205',
                'component' => 'AtlasApValidationEvidenceContract',
                'schema_version' => 'atlas.ap_validation_evidence_contract.v1',
                'purpose' => 'validate_completion_evidence_shape_before_completion_report',
                'allowed_next_steps' => ['AP-203'],
                'blocks_when' => ['validation_evidence_invalid_shape'],
            ],
            [
                'order' => 5,
                'ap' => 'AP-203',
                'component' => 'AtlasApAgentCompletionReport',
                'schema_version' => 'atlas.ap_agent_completion_report.v1',
                'purpose' => 'close_agent_session_with_gate_and_validation_evidence',
                'allowed_next_steps' => [],
                'blocks_when' => ['session_gate_not_ready', 'completion_checklist_incomplete'],
            ],
        ];
    }

    /**
     * @return array<int,array<string,mixed>>
     */
    private function postCompletionReviewChain(): array
    {
        return [
            [
                'order' => 1,
                'ap' => 'AP-206',
                'component' => 'AtlasApAgentWorkflowTransitionPolicy',
                'schema_version' => 'atlas.ap_agent_workflow_transition_policy.v1',
                'purpose' => 'validate_declared_transitions_for_the_primary_agent_trace',
            ],
            [
                'order' => 2,
                'ap' => 'AP-207',
                'component' => 'AtlasApAgentWorkflowTraceAudit',
                'schema_version' => 'atlas.ap_agent_workflow_trace_audit.v1',
                'purpose' => 'audit_primary_agent_trace_before_any_completion_claim',
            ],
            [
                'order' => 3,
                'ap' => 'AP-208',
                'component' => 'AtlasApAgentWorkflowExecutionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_execution_receipt.v1',
                'purpose' => 'combine_trace_audit_and_completion_report_into_execution_receipt',
            ],
            [
                'order' => 4,
                'ap' => 'AP-209',
                'component' => 'AtlasApAgentWorkflowHumanReviewPacket',
                'schema_version' => 'atlas.ap_agent_workflow_human_review_packet.v1',
                'purpose' => 'prepare_human_review_packet_without_accepting_work',
            ],
            [
                'order' => 5,
                'ap' => 'AP-210',
                'component' => 'AtlasApAgentWorkflowHumanDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_human_decision_contract.v1',
                'purpose' => 'normalize_human_accept_request_changes_or_reject_decision',
            ],
            [
                'order' => 6,
                'ap' => 'AP-211',
                'component' => 'AtlasApAgentWorkflowIntegratorHandoffPacket',
                'schema_version' => 'atlas.ap_agent_workflow_integrator_handoff_packet.v1',
                'purpose' => 'handoff_human_accepted_work_to_integrator_review',
            ],
            [
                'order' => 7,
                'ap' => 'AP-212',
                'component' => 'AtlasApAgentWorkflowIntegratorReadinessContract',
                'schema_version' => 'atlas.ap_agent_workflow_integrator_readiness_contract.v1',
                'purpose' => 'require_integrator_evidence_before_manual_integration',
            ],
            [
                'order' => 8,
                'ap' => 'AP-213',
                'component' => 'AtlasApAgentWorkflowManualIntegrationReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_manual_integration_receipt.v1',
                'purpose' => 'normalize_manual_integration_evidence_without_publishing',
            ],
            [
                'order' => 9,
                'ap' => 'AP-214',
                'component' => 'AtlasApAgentWorkflowFinalAuditPacket',
                'schema_version' => 'atlas.ap_agent_workflow_final_audit_packet.v1',
                'purpose' => 'prepare_final_audit_packet_before_closeout',
            ],
            [
                'order' => 10,
                'ap' => 'AP-215',
                'component' => 'AtlasApAgentWorkflowFinalCloseoutDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_final_closeout_decision_contract.v1',
                'purpose' => 'normalize_final_human_closeout_decision_without_publishing',
            ],
            [
                'order' => 11,
                'ap' => 'AP-216',
                'component' => 'AtlasApAgentWorkflowCloseoutAcceptanceReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_closeout_acceptance_receipt.v1',
                'purpose' => 'produce_final_read_only_acceptance_receipt_for_future_release_or_ledger_work',
            ],
            [
                'order' => 12,
                'ap' => 'AP-217',
                'component' => 'AtlasApAgentWorkflowReleaseEvidencePreflight',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_preflight.v1',
                'purpose' => 'validate_closeout_receipt_before_future_release_or_evidence_layer_consumes_it',
            ],
            [
                'order' => 13,
                'ap' => 'AP-218',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceHandoffPacket',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_handoff_packet.v1',
                'purpose' => 'handoff_ready_preflight_to_future_release_or_evidence_owner_without_side_effects',
            ],
            [
                'order' => 14,
                'ap' => 'AP-219',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceCandidateContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_candidate_contract.v1',
                'purpose' => 'shape_release_or_evidence_candidate_for_human_review_without_execution',
            ],
            [
                'order' => 15,
                'ap' => 'AP-220',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceCandidateDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_candidate_decision_contract.v1',
                'purpose' => 'normalize_human_decision_for_release_or_evidence_candidate_without_execution',
            ],
            [
                'order' => 16,
                'ap' => 'AP-221',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceCandidateDecisionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_candidate_decision_receipt.v1',
                'purpose' => 'report_candidate_human_decision_outcome_without_execution',
            ],
            [
                'order' => 17,
                'ap' => 'AP-222',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionReadinessContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_readiness_contract.v1',
                'purpose' => 'validate_final_readiness_for_future_release_or_ledger_execution_ap_without_execution',
            ],
            [
                'order' => 18,
                'ap' => 'AP-223',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunPlanContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_dry_run_plan_contract.v1',
                'purpose' => 'plan_future_dry_run_without_running_it_or_mutating_release_or_ledger_state',
            ],
            [
                'order' => 19,
                'ap' => 'AP-224',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunReviewContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_dry_run_review_contract.v1',
                'purpose' => 'normalize_human_review_of_dry_run_plan_without_running_it_or_mutating_release_or_ledger_state',
            ],
            [
                'order' => 20,
                'ap' => 'AP-225',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunResultEnvelopeContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_dry_run_result_envelope_contract.v1',
                'purpose' => 'seal_declared_dry_run_result_evidence_for_future_human_review_without_execution_or_ledger_write',
            ],
            [
                'order' => 21,
                'ap' => 'AP-226',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceDryRunResultReviewContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_dry_run_result_review_contract.v1',
                'purpose' => 'normalize_human_review_of_dry_run_result_without_release_or_ledger_execution',
            ],
            [
                'order' => 22,
                'ap' => 'AP-227',
                'component' => 'AtlasApAgentWorkflowReleaseEvidencePostDryRunHandoffPacket',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_post_dry_run_handoff_packet.v1',
                'purpose' => 'handoff_accepted_dry_run_result_to_future_release_or_ledger_ap_without_execution',
            ],
            [
                'order' => 23,
                'ap' => 'AP-228',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_consumer_readiness_contract.v1',
                'purpose' => 'validate_future_consumer_readiness_for_release_or_ledger_decision_without_execution',
            ],
            [
                'order' => 24,
                'ap' => 'AP-229',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_consumer_readiness_decision_contract.v1',
                'purpose' => 'normalize_human_decision_for_consumer_readiness_without_release_or_ledger_execution',
            ],
            [
                'order' => 25,
                'ap' => 'AP-230',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceConsumerReadinessDecisionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_consumer_readiness_decision_receipt.v1',
                'purpose' => 'report_consumer_readiness_human_decision_outcome_without_release_or_ledger_execution',
            ],
            [
                'order' => 26,
                'ap' => 'AP-231',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationPreflight',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_authorization_preflight.v1',
                'purpose' => 'preflight_future_execution_authorization_without_authorizing_release_or_ledger_execution',
            ],
            [
                'order' => 27,
                'ap' => 'AP-232',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_authorization_decision_contract.v1',
                'purpose' => 'normalize_human_execution_authorization_decision_without_executing_release_or_ledger_work',
            ],
            [
                'order' => 28,
                'ap' => 'AP-233',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationDecisionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_authorization_decision_receipt.v1',
                'purpose' => 'report_execution_authorization_human_decision_outcome_without_release_or_ledger_execution',
            ],
            [
                'order' => 29,
                'ap' => 'AP-234',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionAuthorizationHandoffPacket',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_authorization_handoff_packet.v1',
                'purpose' => 'handoff_approved_execution_authorization_to_future_execution_ap_without_execution',
            ],
            [
                'order' => 30,
                'ap' => 'AP-235',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationPreflight',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_implementation_preflight.v1',
                'purpose' => 'preflight_future_execution_implementation_without_commands_or_ledger_writes',
            ],
            [
                'order' => 31,
                'ap' => 'AP-236',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_implementation_decision_contract.v1',
                'purpose' => 'normalize_human_execution_implementation_decision_without_executing_authorized_work',
            ],
            [
                'order' => 32,
                'ap' => 'AP-237',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionImplementationDecisionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_implementation_decision_receipt.v1',
                'purpose' => 'report_execution_implementation_human_decision_outcome_without_execution',
            ],
            [
                'order' => 33,
                'ap' => 'AP-238',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationPreflight',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_activation_preflight.v1',
                'purpose' => 'preflight_future_execution_activation_review_without_activation_or_ledger_write',
            ],
            [
                'order' => 34,
                'ap' => 'AP-239',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationDecisionContract',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_activation_decision_contract.v1',
                'purpose' => 'normalize_human_execution_activation_decision_without_activation',
            ],
            [
                'order' => 35,
                'ap' => 'AP-240',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceExecutionActivationDecisionReceipt',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_execution_activation_decision_receipt.v1',
                'purpose' => 'report_execution_activation_human_decision_outcome_without_activation',
            ],
            [
                'order' => 36,
                'ap' => 'AP-241',
                'component' => 'AtlasApAgentWorkflowReleaseEvidenceRuntimeExecutionPreflight',
                'schema_version' => 'atlas.ap_agent_workflow_release_evidence_runtime_execution_preflight.v1',
                'purpose' => 'preflight_future_runtime_execution_review_without_runtime_execution',
            ],
        ];
    }
}
