from __future__ import annotations

from typing import Any, Mapping

from .payload_safety import reject_forbidden_keys_recursive
from .turn_payload import UnsafeVoicePayload


class SupervisedProcessAdapterPacketViolation(RuntimeError):
    """Raised when the process adapter contract is not fail-closed."""


FORBIDDEN_SUPERVISED_PROCESS_ADAPTER_KEYS = {
    "access_token",
    "api_key",
    "api_secret",
    "audio",
    "audio_bytes",
    "audio_raw",
    "direct_llm_provider_call",
    "direct_provider_call",
    "direct_tool_execution",
    "env_file_contents",
    "livekit_token",
    "memory_write",
    "pcm",
    "provider_api_key",
    "raw_audio",
    "raw_audio_bytes",
    "raw_response_text",
    "response_text",
    "secret",
    "secret_value",
    "token",
    "tool_args",
    "tool_call",
    "tts_text",
    "wav",
}


def validate_supervised_process_adapter_packet(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    try:
        reject_forbidden_keys_recursive(
            payload,
            FORBIDDEN_SUPERVISED_PROCESS_ADAPTER_KEYS,
            label="supervised_process_adapter",
        )
    except UnsafeVoicePayload as exc:
        raise SupervisedProcessAdapterPacketViolation(str(exc)) from exc

    _expect("schema_version", payload.get("schema_version"), "atlas.voice_realtime.supervised_process_adapter.v1")
    _expect("launch_allowed", payload.get("launch_allowed"), False)
    _expect("process_launch_attempted", payload.get("process_launch_attempted"), False)
    _expect("daemon_started", payload.get("daemon_started"), False)
    _expect("subprocess_module_imported", payload.get("subprocess_module_imported"), False)
    _expect("livekit_sdk_imported", payload.get("livekit_sdk_imported"), False)

    gates = _expect_mapping("gates", payload.get("gates"))
    _expect("gates.launch_disabled", gates.get("launch_disabled"), True)
    _expect("gates.secrets_redacted", gates.get("secrets_redacted"), True)
    _expect("gates.provider_calls_forbidden", gates.get("provider_calls_forbidden"), True)
    _expect("gates.tool_calls_forbidden", gates.get("tool_calls_forbidden"), True)

    env_contract = _expect_mapping("managed_environment_contract", payload.get("managed_environment_contract"))
    _expect("managed_environment_contract.schema_version", env_contract.get("schema_version"), "atlas.voice_realtime.managed_env_contract.v1")
    _expect("managed_environment_contract.env_value_logging_allowed", env_contract.get("env_value_logging_allowed"), False)
    _expect("managed_environment_contract.env_file_write_attempted", env_contract.get("env_file_write_attempted"), False)
    _expect("managed_environment_contract.env_file_written", env_contract.get("env_file_written"), False)
    _expect("managed_environment_contract.secret_values_present_in_output", env_contract.get("secret_values_present_in_output"), False)

    launch_auth = _expect_mapping("launch_authorization_contract", payload.get("launch_authorization_contract"))
    _expect("launch_authorization_contract.schema_version", launch_auth.get("schema_version"), "atlas.voice_realtime.launch_authorization_contract.v1")
    _expect("launch_authorization_contract.launch_allowed", launch_auth.get("launch_allowed"), False)
    _expect("launch_authorization_contract.process_launch_attempted", launch_auth.get("process_launch_attempted"), False)
    _expect("launch_authorization_contract.daemon_started", launch_auth.get("daemon_started"), False)
    _expect("launch_authorization_contract.decision_receipt_required", launch_auth.get("decision_receipt_required"), True)

    launch_execution = _expect_mapping("supervised_launch_execution", payload.get("supervised_launch_execution"))
    _expect("supervised_launch_execution.schema_version", launch_execution.get("schema_version"), "atlas.voice_realtime.supervised_launch_execution.v1")
    _expect("supervised_launch_execution.subprocess_launch_implemented", launch_execution.get("subprocess_launch_implemented"), False)
    _expect("supervised_launch_execution.process_launch_attempted", launch_execution.get("process_launch_attempted"), False)
    _expect("supervised_launch_execution.daemon_started", launch_execution.get("daemon_started"), False)
    _expect("supervised_launch_execution.process_launch_allowed", launch_execution.get("process_launch_allowed"), False)
    _expect("supervised_launch_execution.subprocess_module_imported", launch_execution.get("subprocess_module_imported"), False)
    _expect("supervised_launch_execution.livekit_sdk_imported", launch_execution.get("livekit_sdk_imported"), False)

    start_contract = _expect_mapping("subprocess_start_contract", payload.get("subprocess_start_contract"))
    _expect("subprocess_start_contract.schema_version", start_contract.get("schema_version"), "atlas.voice_realtime.subprocess_start_contract.v1")
    _expect("subprocess_start_contract.subprocess_launch_implemented", start_contract.get("subprocess_launch_implemented"), False)
    _expect("subprocess_start_contract.process_launch_attempted", start_contract.get("process_launch_attempted"), False)
    _expect("subprocess_start_contract.daemon_started", start_contract.get("daemon_started"), False)
    _expect("subprocess_start_contract.process_launch_allowed", start_contract.get("process_launch_allowed"), False)
    _expect("subprocess_start_contract.subprocess_module_imported", start_contract.get("subprocess_module_imported"), False)
    _expect("subprocess_start_contract.livekit_sdk_imported", start_contract.get("livekit_sdk_imported"), False)
    _expect("subprocess_start_contract.provider_calls_made", start_contract.get("provider_calls_made"), False)
    _expect("subprocess_start_contract.tool_calls_made", start_contract.get("tool_calls_made"), False)
    _expect("subprocess_start_contract.raw_audio_touched", start_contract.get("raw_audio_touched"), False)

    reviewed_start = _expect_mapping("reviewed_subprocess_start_execution", payload.get("reviewed_subprocess_start_execution"))
    _expect("reviewed_subprocess_start_execution.schema_version", reviewed_start.get("schema_version"), "atlas.voice_realtime.reviewed_subprocess_start_execution.v1")
    _expect("reviewed_subprocess_start_execution.reviewed_subprocess_start_execution_implemented", reviewed_start.get("reviewed_subprocess_start_execution_implemented"), True)
    _expect("reviewed_subprocess_start_execution.real_subprocess_start_implemented", reviewed_start.get("real_subprocess_start_implemented"), False)
    _expect("reviewed_subprocess_start_execution.subprocess_launch_implemented", reviewed_start.get("subprocess_launch_implemented"), False)
    _expect("reviewed_subprocess_start_execution.process_launch_attempted", reviewed_start.get("process_launch_attempted"), False)
    _expect("reviewed_subprocess_start_execution.daemon_started", reviewed_start.get("daemon_started"), False)
    _expect("reviewed_subprocess_start_execution.process_launch_allowed", reviewed_start.get("process_launch_allowed"), False)
    _expect("reviewed_subprocess_start_execution.subprocess_module_imported", reviewed_start.get("subprocess_module_imported"), False)
    _expect("reviewed_subprocess_start_execution.livekit_sdk_imported", reviewed_start.get("livekit_sdk_imported"), False)
    _expect("reviewed_subprocess_start_execution.provider_calls_made", reviewed_start.get("provider_calls_made"), False)
    _expect("reviewed_subprocess_start_execution.tool_calls_made", reviewed_start.get("tool_calls_made"), False)
    _expect("reviewed_subprocess_start_execution.raw_audio_touched", reviewed_start.get("raw_audio_touched"), False)

    real_start_adapter = _expect_mapping("real_start_adapter_disabled", payload.get("real_start_adapter_disabled"))
    _expect("real_start_adapter_disabled.schema_version", real_start_adapter.get("schema_version"), "atlas.voice_realtime.real_start_adapter_disabled.v1")
    _expect("real_start_adapter_disabled.real_start_adapter_contract_implemented", real_start_adapter.get("real_start_adapter_contract_implemented"), True)
    _expect("real_start_adapter_disabled.real_start_adapter_enabled", real_start_adapter.get("real_start_adapter_enabled"), False)
    _expect("real_start_adapter_disabled.real_subprocess_start_implemented", real_start_adapter.get("real_subprocess_start_implemented"), False)
    _expect("real_start_adapter_disabled.process_launch_attempted", real_start_adapter.get("process_launch_attempted"), False)
    _expect("real_start_adapter_disabled.daemon_started", real_start_adapter.get("daemon_started"), False)
    _expect("real_start_adapter_disabled.process_launch_allowed", real_start_adapter.get("process_launch_allowed"), False)
    _expect("real_start_adapter_disabled.subprocess_module_imported", real_start_adapter.get("subprocess_module_imported"), False)
    _expect("real_start_adapter_disabled.livekit_sdk_imported", real_start_adapter.get("livekit_sdk_imported"), False)
    _expect("real_start_adapter_disabled.provider_calls_made", real_start_adapter.get("provider_calls_made"), False)
    _expect("real_start_adapter_disabled.tool_calls_made", real_start_adapter.get("tool_calls_made"), False)
    _expect("real_start_adapter_disabled.raw_audio_touched", real_start_adapter.get("raw_audio_touched"), False)

    enablement_gate = _expect_mapping("real_start_enablement_gate", payload.get("real_start_enablement_gate"))
    _expect("real_start_enablement_gate.schema_version", enablement_gate.get("schema_version"), "atlas.voice_realtime.real_start_enablement_gate.v1")
    _expect("real_start_enablement_gate.real_start_enablement_gate_implemented", enablement_gate.get("real_start_enablement_gate_implemented"), True)
    _expect("real_start_enablement_gate.real_start_adapter_enabled", enablement_gate.get("real_start_adapter_enabled"), False)
    _expect("real_start_enablement_gate.start_execution_allowed", enablement_gate.get("start_execution_allowed"), False)
    _expect("real_start_enablement_gate.real_subprocess_start_implemented", enablement_gate.get("real_subprocess_start_implemented"), False)
    _expect("real_start_enablement_gate.process_launch_attempted", enablement_gate.get("process_launch_attempted"), False)
    _expect("real_start_enablement_gate.daemon_started", enablement_gate.get("daemon_started"), False)
    _expect("real_start_enablement_gate.process_launch_allowed", enablement_gate.get("process_launch_allowed"), False)
    _expect("real_start_enablement_gate.subprocess_module_imported", enablement_gate.get("subprocess_module_imported"), False)
    _expect("real_start_enablement_gate.livekit_sdk_imported", enablement_gate.get("livekit_sdk_imported"), False)
    _expect("real_start_enablement_gate.provider_calls_made", enablement_gate.get("provider_calls_made"), False)
    _expect("real_start_enablement_gate.tool_calls_made", enablement_gate.get("tool_calls_made"), False)
    _expect("real_start_enablement_gate.raw_audio_touched", enablement_gate.get("raw_audio_touched"), False)

    policy_review = _expect_mapping("runtime_policy_enablement_review", payload.get("runtime_policy_enablement_review"))
    _expect("runtime_policy_enablement_review.schema_version", policy_review.get("schema_version"), "atlas.voice_realtime.runtime_policy_enablement_review.v1")
    _expect("runtime_policy_enablement_review.runtime_policy_enablement_review_implemented", policy_review.get("runtime_policy_enablement_review_implemented"), True)
    _expect("runtime_policy_enablement_review.runtime_policy_start_enabled", policy_review.get("runtime_policy_start_enabled"), False)
    _expect("runtime_policy_enablement_review.real_start_adapter_enabled", policy_review.get("real_start_adapter_enabled"), False)
    _expect("runtime_policy_enablement_review.start_execution_allowed", policy_review.get("start_execution_allowed"), False)
    _expect("runtime_policy_enablement_review.real_subprocess_start_implemented", policy_review.get("real_subprocess_start_implemented"), False)
    _expect("runtime_policy_enablement_review.process_launch_attempted", policy_review.get("process_launch_attempted"), False)
    _expect("runtime_policy_enablement_review.daemon_started", policy_review.get("daemon_started"), False)
    _expect("runtime_policy_enablement_review.process_launch_allowed", policy_review.get("process_launch_allowed"), False)
    _expect("runtime_policy_enablement_review.subprocess_module_imported", policy_review.get("subprocess_module_imported"), False)
    _expect("runtime_policy_enablement_review.livekit_sdk_imported", policy_review.get("livekit_sdk_imported"), False)
    _expect("runtime_policy_enablement_review.provider_calls_made", policy_review.get("provider_calls_made"), False)
    _expect("runtime_policy_enablement_review.tool_calls_made", policy_review.get("tool_calls_made"), False)
    _expect("runtime_policy_enablement_review.raw_audio_touched", policy_review.get("raw_audio_touched"), False)

    adapter_review = _expect_mapping("real_start_adapter_review_contract", payload.get("real_start_adapter_review_contract"))
    _expect("real_start_adapter_review_contract.schema_version", adapter_review.get("schema_version"), "atlas.voice_realtime.real_start_adapter_review_contract.v1")
    _expect("real_start_adapter_review_contract.real_start_adapter_review_contract_implemented", adapter_review.get("real_start_adapter_review_contract_implemented"), True)
    _expect("real_start_adapter_review_contract.runtime_policy_start_enabled", adapter_review.get("runtime_policy_start_enabled"), False)
    _expect("real_start_adapter_review_contract.real_start_adapter_enabled", adapter_review.get("real_start_adapter_enabled"), False)
    _expect("real_start_adapter_review_contract.start_execution_allowed", adapter_review.get("start_execution_allowed"), False)
    _expect("real_start_adapter_review_contract.real_subprocess_start_implemented", adapter_review.get("real_subprocess_start_implemented"), False)
    _expect("real_start_adapter_review_contract.process_launch_attempted", adapter_review.get("process_launch_attempted"), False)
    _expect("real_start_adapter_review_contract.daemon_started", adapter_review.get("daemon_started"), False)
    _expect("real_start_adapter_review_contract.process_launch_allowed", adapter_review.get("process_launch_allowed"), False)
    _expect("real_start_adapter_review_contract.subprocess_module_imported", adapter_review.get("subprocess_module_imported"), False)
    _expect("real_start_adapter_review_contract.livekit_sdk_imported", adapter_review.get("livekit_sdk_imported"), False)
    _expect("real_start_adapter_review_contract.provider_calls_made", adapter_review.get("provider_calls_made"), False)
    _expect("real_start_adapter_review_contract.tool_calls_made", adapter_review.get("tool_calls_made"), False)
    _expect("real_start_adapter_review_contract.raw_audio_touched", adapter_review.get("raw_audio_touched"), False)

    real_execution = _expect_mapping("reviewed_real_start_execution_contract", payload.get("reviewed_real_start_execution_contract"))
    _expect("reviewed_real_start_execution_contract.schema_version", real_execution.get("schema_version"), "atlas.voice_realtime.reviewed_real_start_execution_contract.v1")
    _expect("reviewed_real_start_execution_contract.reviewed_real_start_execution_contract_implemented", real_execution.get("reviewed_real_start_execution_contract_implemented"), True)
    _expect("reviewed_real_start_execution_contract.runtime_policy_start_enabled", real_execution.get("runtime_policy_start_enabled"), False)
    _expect("reviewed_real_start_execution_contract.real_start_adapter_enabled", real_execution.get("real_start_adapter_enabled"), False)
    _expect("reviewed_real_start_execution_contract.start_execution_allowed", real_execution.get("start_execution_allowed"), False)
    _expect("reviewed_real_start_execution_contract.real_subprocess_start_implemented", real_execution.get("real_subprocess_start_implemented"), False)
    _expect("reviewed_real_start_execution_contract.process_launch_attempted", real_execution.get("process_launch_attempted"), False)
    _expect("reviewed_real_start_execution_contract.daemon_started", real_execution.get("daemon_started"), False)
    _expect("reviewed_real_start_execution_contract.process_launch_allowed", real_execution.get("process_launch_allowed"), False)
    _expect("reviewed_real_start_execution_contract.subprocess_module_imported", real_execution.get("subprocess_module_imported"), False)
    _expect("reviewed_real_start_execution_contract.livekit_sdk_imported", real_execution.get("livekit_sdk_imported"), False)
    _expect("reviewed_real_start_execution_contract.provider_calls_made", real_execution.get("provider_calls_made"), False)
    _expect("reviewed_real_start_execution_contract.tool_calls_made", real_execution.get("tool_calls_made"), False)
    _expect("reviewed_real_start_execution_contract.raw_audio_touched", real_execution.get("raw_audio_touched"), False)

    final_start_executor = _expect_mapping("final_start_executor_disabled", payload.get("final_start_executor_disabled"))
    _expect("final_start_executor_disabled.schema_version", final_start_executor.get("schema_version"), "atlas.voice_realtime.final_start_executor_disabled.v1")
    _expect("final_start_executor_disabled.final_start_executor_contract_implemented", final_start_executor.get("final_start_executor_contract_implemented"), True)
    _expect("final_start_executor_disabled.final_start_executor_enabled", final_start_executor.get("final_start_executor_enabled"), False)
    _expect("final_start_executor_disabled.runtime_policy_start_enabled", final_start_executor.get("runtime_policy_start_enabled"), False)
    _expect("final_start_executor_disabled.real_start_adapter_enabled", final_start_executor.get("real_start_adapter_enabled"), False)
    _expect("final_start_executor_disabled.start_execution_allowed", final_start_executor.get("start_execution_allowed"), False)
    _expect("final_start_executor_disabled.real_subprocess_start_implemented", final_start_executor.get("real_subprocess_start_implemented"), False)
    _expect("final_start_executor_disabled.process_launch_attempted", final_start_executor.get("process_launch_attempted"), False)
    _expect("final_start_executor_disabled.daemon_started", final_start_executor.get("daemon_started"), False)
    _expect("final_start_executor_disabled.process_launch_allowed", final_start_executor.get("process_launch_allowed"), False)
    _expect("final_start_executor_disabled.subprocess_module_imported", final_start_executor.get("subprocess_module_imported"), False)
    _expect("final_start_executor_disabled.livekit_sdk_imported", final_start_executor.get("livekit_sdk_imported"), False)
    _expect("final_start_executor_disabled.provider_calls_made", final_start_executor.get("provider_calls_made"), False)
    _expect("final_start_executor_disabled.tool_calls_made", final_start_executor.get("tool_calls_made"), False)
    _expect("final_start_executor_disabled.raw_audio_touched", final_start_executor.get("raw_audio_touched"), False)

    final_enablement = _expect_mapping("final_start_executor_enablement_gate", payload.get("final_start_executor_enablement_gate"))
    _expect("final_start_executor_enablement_gate.schema_version", final_enablement.get("schema_version"), "atlas.voice_realtime.final_start_executor_enablement_gate.v1")
    _expect("final_start_executor_enablement_gate.final_start_executor_enablement_gate_implemented", final_enablement.get("final_start_executor_enablement_gate_implemented"), True)
    _expect("final_start_executor_enablement_gate.final_start_executor_enabled", final_enablement.get("final_start_executor_enabled"), False)
    _expect("final_start_executor_enablement_gate.runtime_policy_start_enabled", final_enablement.get("runtime_policy_start_enabled"), False)
    _expect("final_start_executor_enablement_gate.real_start_adapter_enabled", final_enablement.get("real_start_adapter_enabled"), False)
    _expect("final_start_executor_enablement_gate.start_execution_allowed", final_enablement.get("start_execution_allowed"), False)
    _expect("final_start_executor_enablement_gate.real_subprocess_start_implemented", final_enablement.get("real_subprocess_start_implemented"), False)
    _expect("final_start_executor_enablement_gate.process_launch_attempted", final_enablement.get("process_launch_attempted"), False)
    _expect("final_start_executor_enablement_gate.daemon_started", final_enablement.get("daemon_started"), False)
    _expect("final_start_executor_enablement_gate.process_launch_allowed", final_enablement.get("process_launch_allowed"), False)
    _expect("final_start_executor_enablement_gate.subprocess_module_imported", final_enablement.get("subprocess_module_imported"), False)
    _expect("final_start_executor_enablement_gate.livekit_sdk_imported", final_enablement.get("livekit_sdk_imported"), False)
    _expect("final_start_executor_enablement_gate.provider_calls_made", final_enablement.get("provider_calls_made"), False)
    _expect("final_start_executor_enablement_gate.tool_calls_made", final_enablement.get("tool_calls_made"), False)
    _expect("final_start_executor_enablement_gate.raw_audio_touched", final_enablement.get("raw_audio_touched"), False)

    start_review = _expect_mapping("supervised_start_execution_review", payload.get("supervised_start_execution_review"))
    _expect("supervised_start_execution_review.schema_version", start_review.get("schema_version"), "atlas.voice_realtime.supervised_start_execution_review.v1")
    _expect("supervised_start_execution_review.supervised_start_execution_review_implemented", start_review.get("supervised_start_execution_review_implemented"), True)
    _expect("supervised_start_execution_review.final_start_executor_enabled", start_review.get("final_start_executor_enabled"), False)
    _expect("supervised_start_execution_review.runtime_policy_start_enabled", start_review.get("runtime_policy_start_enabled"), False)
    _expect("supervised_start_execution_review.real_start_adapter_enabled", start_review.get("real_start_adapter_enabled"), False)
    _expect("supervised_start_execution_review.start_execution_allowed", start_review.get("start_execution_allowed"), False)
    _expect("supervised_start_execution_review.real_subprocess_start_implemented", start_review.get("real_subprocess_start_implemented"), False)
    _expect("supervised_start_execution_review.process_launch_attempted", start_review.get("process_launch_attempted"), False)
    _expect("supervised_start_execution_review.daemon_started", start_review.get("daemon_started"), False)
    _expect("supervised_start_execution_review.process_launch_allowed", start_review.get("process_launch_allowed"), False)
    _expect("supervised_start_execution_review.subprocess_module_imported", start_review.get("subprocess_module_imported"), False)
    _expect("supervised_start_execution_review.livekit_sdk_imported", start_review.get("livekit_sdk_imported"), False)
    _expect("supervised_start_execution_review.provider_calls_made", start_review.get("provider_calls_made"), False)
    _expect("supervised_start_execution_review.tool_calls_made", start_review.get("tool_calls_made"), False)
    _expect("supervised_start_execution_review.raw_audio_touched", start_review.get("raw_audio_touched"), False)

    real_start_contract = _expect_mapping("real_start_execution_contract", payload.get("real_start_execution_contract"))
    _expect("real_start_execution_contract.schema_version", real_start_contract.get("schema_version"), "atlas.voice_realtime.real_start_execution_contract.v1")
    _expect("real_start_execution_contract.real_start_execution_contract_implemented", real_start_contract.get("real_start_execution_contract_implemented"), True)
    _expect("real_start_execution_contract.guarded_start_executor_implemented", real_start_contract.get("guarded_start_executor_implemented"), False)
    _expect("real_start_execution_contract.final_start_executor_enabled", real_start_contract.get("final_start_executor_enabled"), False)
    _expect("real_start_execution_contract.runtime_policy_start_enabled", real_start_contract.get("runtime_policy_start_enabled"), False)
    _expect("real_start_execution_contract.real_start_adapter_enabled", real_start_contract.get("real_start_adapter_enabled"), False)
    _expect("real_start_execution_contract.start_execution_allowed", real_start_contract.get("start_execution_allowed"), False)
    _expect("real_start_execution_contract.real_subprocess_start_implemented", real_start_contract.get("real_subprocess_start_implemented"), False)
    _expect("real_start_execution_contract.process_launch_attempted", real_start_contract.get("process_launch_attempted"), False)
    _expect("real_start_execution_contract.daemon_started", real_start_contract.get("daemon_started"), False)
    _expect("real_start_execution_contract.process_launch_allowed", real_start_contract.get("process_launch_allowed"), False)
    _expect("real_start_execution_contract.subprocess_module_imported", real_start_contract.get("subprocess_module_imported"), False)
    _expect("real_start_execution_contract.livekit_sdk_imported", real_start_contract.get("livekit_sdk_imported"), False)
    _expect("real_start_execution_contract.provider_calls_made", real_start_contract.get("provider_calls_made"), False)
    _expect("real_start_execution_contract.tool_calls_made", real_start_contract.get("tool_calls_made"), False)
    _expect("real_start_execution_contract.raw_audio_touched", real_start_contract.get("raw_audio_touched"), False)

    guarded_start_executor = _expect_mapping("guarded_start_executor_disabled", payload.get("guarded_start_executor_disabled"))
    _expect("guarded_start_executor_disabled.schema_version", guarded_start_executor.get("schema_version"), "atlas.voice_realtime.guarded_start_executor_disabled.v1")
    _expect("guarded_start_executor_disabled.guarded_start_executor_contract_implemented", guarded_start_executor.get("guarded_start_executor_contract_implemented"), True)
    _expect("guarded_start_executor_disabled.guarded_start_executor_enabled", guarded_start_executor.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_executor_disabled.guarded_start_executor_implemented", guarded_start_executor.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_executor_disabled.final_start_executor_enabled", guarded_start_executor.get("final_start_executor_enabled"), False)
    _expect("guarded_start_executor_disabled.runtime_policy_start_enabled", guarded_start_executor.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_executor_disabled.real_start_adapter_enabled", guarded_start_executor.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_executor_disabled.start_execution_allowed", guarded_start_executor.get("start_execution_allowed"), False)
    _expect("guarded_start_executor_disabled.real_subprocess_start_implemented", guarded_start_executor.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_executor_disabled.process_launch_attempted", guarded_start_executor.get("process_launch_attempted"), False)
    _expect("guarded_start_executor_disabled.daemon_started", guarded_start_executor.get("daemon_started"), False)
    _expect("guarded_start_executor_disabled.process_launch_allowed", guarded_start_executor.get("process_launch_allowed"), False)
    _expect("guarded_start_executor_disabled.subprocess_module_imported", guarded_start_executor.get("subprocess_module_imported"), False)
    _expect("guarded_start_executor_disabled.livekit_sdk_imported", guarded_start_executor.get("livekit_sdk_imported"), False)
    _expect("guarded_start_executor_disabled.provider_calls_made", guarded_start_executor.get("provider_calls_made"), False)
    _expect("guarded_start_executor_disabled.tool_calls_made", guarded_start_executor.get("tool_calls_made"), False)
    _expect("guarded_start_executor_disabled.raw_audio_touched", guarded_start_executor.get("raw_audio_touched"), False)

    guarded_enablement = _expect_mapping("guarded_start_executor_enablement_gate", payload.get("guarded_start_executor_enablement_gate"))
    _expect("guarded_start_executor_enablement_gate.schema_version", guarded_enablement.get("schema_version"), "atlas.voice_realtime.guarded_start_executor_enablement_gate.v1")
    _expect("guarded_start_executor_enablement_gate.guarded_start_executor_enablement_gate_implemented", guarded_enablement.get("guarded_start_executor_enablement_gate_implemented"), True)
    _expect("guarded_start_executor_enablement_gate.guarded_start_executor_enabled", guarded_enablement.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_executor_enablement_gate.guarded_start_executor_implemented", guarded_enablement.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_executor_enablement_gate.final_start_executor_enabled", guarded_enablement.get("final_start_executor_enabled"), False)
    _expect("guarded_start_executor_enablement_gate.runtime_policy_start_enabled", guarded_enablement.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_executor_enablement_gate.real_start_adapter_enabled", guarded_enablement.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_executor_enablement_gate.start_execution_allowed", guarded_enablement.get("start_execution_allowed"), False)
    _expect("guarded_start_executor_enablement_gate.real_subprocess_start_implemented", guarded_enablement.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_executor_enablement_gate.process_launch_attempted", guarded_enablement.get("process_launch_attempted"), False)
    _expect("guarded_start_executor_enablement_gate.daemon_started", guarded_enablement.get("daemon_started"), False)
    _expect("guarded_start_executor_enablement_gate.process_launch_allowed", guarded_enablement.get("process_launch_allowed"), False)
    _expect("guarded_start_executor_enablement_gate.subprocess_module_imported", guarded_enablement.get("subprocess_module_imported"), False)
    _expect("guarded_start_executor_enablement_gate.livekit_sdk_imported", guarded_enablement.get("livekit_sdk_imported"), False)
    _expect("guarded_start_executor_enablement_gate.provider_calls_made", guarded_enablement.get("provider_calls_made"), False)
    _expect("guarded_start_executor_enablement_gate.tool_calls_made", guarded_enablement.get("tool_calls_made"), False)
    _expect("guarded_start_executor_enablement_gate.raw_audio_touched", guarded_enablement.get("raw_audio_touched"), False)

    reviewed_guarded = _expect_mapping("reviewed_guarded_start_execution_contract", payload.get("reviewed_guarded_start_execution_contract"))
    _expect("reviewed_guarded_start_execution_contract.schema_version", reviewed_guarded.get("schema_version"), "atlas.voice_realtime.reviewed_guarded_start_execution_contract.v1")
    _expect("reviewed_guarded_start_execution_contract.reviewed_guarded_start_execution_contract_implemented", reviewed_guarded.get("reviewed_guarded_start_execution_contract_implemented"), True)
    _expect("reviewed_guarded_start_execution_contract.guarded_start_executor_enabled", reviewed_guarded.get("guarded_start_executor_enabled"), False)
    _expect("reviewed_guarded_start_execution_contract.guarded_start_executor_implemented", reviewed_guarded.get("guarded_start_executor_implemented"), False)
    _expect("reviewed_guarded_start_execution_contract.final_start_executor_enabled", reviewed_guarded.get("final_start_executor_enabled"), False)
    _expect("reviewed_guarded_start_execution_contract.runtime_policy_start_enabled", reviewed_guarded.get("runtime_policy_start_enabled"), False)
    _expect("reviewed_guarded_start_execution_contract.real_start_adapter_enabled", reviewed_guarded.get("real_start_adapter_enabled"), False)
    _expect("reviewed_guarded_start_execution_contract.start_execution_allowed", reviewed_guarded.get("start_execution_allowed"), False)
    _expect("reviewed_guarded_start_execution_contract.real_subprocess_start_implemented", reviewed_guarded.get("real_subprocess_start_implemented"), False)
    _expect("reviewed_guarded_start_execution_contract.process_launch_attempted", reviewed_guarded.get("process_launch_attempted"), False)
    _expect("reviewed_guarded_start_execution_contract.daemon_started", reviewed_guarded.get("daemon_started"), False)
    _expect("reviewed_guarded_start_execution_contract.process_launch_allowed", reviewed_guarded.get("process_launch_allowed"), False)
    _expect("reviewed_guarded_start_execution_contract.subprocess_module_imported", reviewed_guarded.get("subprocess_module_imported"), False)
    _expect("reviewed_guarded_start_execution_contract.livekit_sdk_imported", reviewed_guarded.get("livekit_sdk_imported"), False)
    _expect("reviewed_guarded_start_execution_contract.provider_calls_made", reviewed_guarded.get("provider_calls_made"), False)
    _expect("reviewed_guarded_start_execution_contract.tool_calls_made", reviewed_guarded.get("tool_calls_made"), False)
    _expect("reviewed_guarded_start_execution_contract.raw_audio_touched", reviewed_guarded.get("raw_audio_touched"), False)

    dry_run = _expect_mapping("guarded_start_dry_run_contract", payload.get("guarded_start_dry_run_contract"))
    _expect("guarded_start_dry_run_contract.schema_version", dry_run.get("schema_version"), "atlas.voice_realtime.guarded_start_dry_run_contract.v1")
    _expect("guarded_start_dry_run_contract.guarded_start_dry_run_contract_implemented", dry_run.get("guarded_start_dry_run_contract_implemented"), True)
    _expect("guarded_start_dry_run_contract.dry_run_only", dry_run.get("dry_run_only"), True)
    _expect("guarded_start_dry_run_contract.guarded_start_executor_enabled", dry_run.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_dry_run_contract.guarded_start_executor_implemented", dry_run.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_dry_run_contract.final_start_executor_enabled", dry_run.get("final_start_executor_enabled"), False)
    _expect("guarded_start_dry_run_contract.runtime_policy_start_enabled", dry_run.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_dry_run_contract.real_start_adapter_enabled", dry_run.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_dry_run_contract.start_execution_allowed", dry_run.get("start_execution_allowed"), False)
    _expect("guarded_start_dry_run_contract.real_subprocess_start_implemented", dry_run.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_dry_run_contract.process_launch_attempted", dry_run.get("process_launch_attempted"), False)
    _expect("guarded_start_dry_run_contract.daemon_started", dry_run.get("daemon_started"), False)
    _expect("guarded_start_dry_run_contract.process_launch_allowed", dry_run.get("process_launch_allowed"), False)
    _expect("guarded_start_dry_run_contract.subprocess_module_imported", dry_run.get("subprocess_module_imported"), False)
    _expect("guarded_start_dry_run_contract.livekit_sdk_imported", dry_run.get("livekit_sdk_imported"), False)
    _expect("guarded_start_dry_run_contract.provider_calls_made", dry_run.get("provider_calls_made"), False)
    _expect("guarded_start_dry_run_contract.tool_calls_made", dry_run.get("tool_calls_made"), False)
    _expect("guarded_start_dry_run_contract.raw_audio_touched", dry_run.get("raw_audio_touched"), False)

    simulation = _expect_mapping("guarded_start_simulation_contract", payload.get("guarded_start_simulation_contract"))
    _expect("guarded_start_simulation_contract.schema_version", simulation.get("schema_version"), "atlas.voice_realtime.guarded_start_simulation_contract.v1")
    _expect("guarded_start_simulation_contract.guarded_start_simulation_contract_implemented", simulation.get("guarded_start_simulation_contract_implemented"), True)
    _expect("guarded_start_simulation_contract.simulation_only", simulation.get("simulation_only"), True)
    _expect("guarded_start_simulation_contract.dry_run_only", simulation.get("dry_run_only"), True)
    _expect("guarded_start_simulation_contract.guarded_start_executor_enabled", simulation.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_simulation_contract.guarded_start_executor_implemented", simulation.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_simulation_contract.final_start_executor_enabled", simulation.get("final_start_executor_enabled"), False)
    _expect("guarded_start_simulation_contract.runtime_policy_start_enabled", simulation.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_simulation_contract.real_start_adapter_enabled", simulation.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_simulation_contract.start_execution_allowed", simulation.get("start_execution_allowed"), False)
    _expect("guarded_start_simulation_contract.real_subprocess_start_implemented", simulation.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_simulation_contract.process_launch_attempted", simulation.get("process_launch_attempted"), False)
    _expect("guarded_start_simulation_contract.daemon_started", simulation.get("daemon_started"), False)
    _expect("guarded_start_simulation_contract.process_launch_allowed", simulation.get("process_launch_allowed"), False)
    _expect("guarded_start_simulation_contract.subprocess_module_imported", simulation.get("subprocess_module_imported"), False)
    _expect("guarded_start_simulation_contract.livekit_sdk_imported", simulation.get("livekit_sdk_imported"), False)
    _expect("guarded_start_simulation_contract.provider_calls_made", simulation.get("provider_calls_made"), False)
    _expect("guarded_start_simulation_contract.tool_calls_made", simulation.get("tool_calls_made"), False)
    _expect("guarded_start_simulation_contract.raw_audio_touched", simulation.get("raw_audio_touched"), False)

    handoff = _expect_mapping("guarded_start_runtime_handoff_contract", payload.get("guarded_start_runtime_handoff_contract"))
    _expect("guarded_start_runtime_handoff_contract.schema_version", handoff.get("schema_version"), "atlas.voice_realtime.guarded_start_runtime_handoff_contract.v1")
    _expect("guarded_start_runtime_handoff_contract.guarded_start_runtime_handoff_contract_implemented", handoff.get("guarded_start_runtime_handoff_contract_implemented"), True)
    _expect("guarded_start_runtime_handoff_contract.runtime_handoff_contract_only", handoff.get("runtime_handoff_contract_only"), True)
    _expect("guarded_start_runtime_handoff_contract.guarded_start_executor_enabled", handoff.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_runtime_handoff_contract.guarded_start_executor_implemented", handoff.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_runtime_handoff_contract.final_start_executor_enabled", handoff.get("final_start_executor_enabled"), False)
    _expect("guarded_start_runtime_handoff_contract.runtime_policy_start_enabled", handoff.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_runtime_handoff_contract.real_start_adapter_enabled", handoff.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_runtime_handoff_contract.start_execution_allowed", handoff.get("start_execution_allowed"), False)
    _expect("guarded_start_runtime_handoff_contract.real_subprocess_start_implemented", handoff.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_runtime_handoff_contract.process_launch_attempted", handoff.get("process_launch_attempted"), False)
    _expect("guarded_start_runtime_handoff_contract.daemon_started", handoff.get("daemon_started"), False)
    _expect("guarded_start_runtime_handoff_contract.process_launch_allowed", handoff.get("process_launch_allowed"), False)
    _expect("guarded_start_runtime_handoff_contract.subprocess_module_imported", handoff.get("subprocess_module_imported"), False)
    _expect("guarded_start_runtime_handoff_contract.livekit_sdk_imported", handoff.get("livekit_sdk_imported"), False)
    _expect("guarded_start_runtime_handoff_contract.provider_calls_made", handoff.get("provider_calls_made"), False)
    _expect("guarded_start_runtime_handoff_contract.tool_calls_made", handoff.get("tool_calls_made"), False)
    _expect("guarded_start_runtime_handoff_contract.raw_audio_touched", handoff.get("raw_audio_touched"), False)

    policy_patch = _expect_mapping("guarded_start_policy_patch_review_contract", payload.get("guarded_start_policy_patch_review_contract"))
    _expect("guarded_start_policy_patch_review_contract.schema_version", policy_patch.get("schema_version"), "atlas.voice_realtime.guarded_start_policy_patch_review_contract.v1")
    _expect("guarded_start_policy_patch_review_contract.guarded_start_policy_patch_review_contract_implemented", policy_patch.get("guarded_start_policy_patch_review_contract_implemented"), True)
    _expect("guarded_start_policy_patch_review_contract.policy_patch_review_only", policy_patch.get("policy_patch_review_only"), True)
    _expect("guarded_start_policy_patch_review_contract.guarded_start_executor_enabled", policy_patch.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_policy_patch_review_contract.guarded_start_executor_implemented", policy_patch.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_policy_patch_review_contract.final_start_executor_enabled", policy_patch.get("final_start_executor_enabled"), False)
    _expect("guarded_start_policy_patch_review_contract.runtime_policy_start_enabled", policy_patch.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_policy_patch_review_contract.real_start_adapter_enabled", policy_patch.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_policy_patch_review_contract.start_execution_allowed", policy_patch.get("start_execution_allowed"), False)
    _expect("guarded_start_policy_patch_review_contract.real_subprocess_start_implemented", policy_patch.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_policy_patch_review_contract.process_launch_attempted", policy_patch.get("process_launch_attempted"), False)
    _expect("guarded_start_policy_patch_review_contract.daemon_started", policy_patch.get("daemon_started"), False)
    _expect("guarded_start_policy_patch_review_contract.process_launch_allowed", policy_patch.get("process_launch_allowed"), False)
    _expect("guarded_start_policy_patch_review_contract.subprocess_module_imported", policy_patch.get("subprocess_module_imported"), False)
    _expect("guarded_start_policy_patch_review_contract.livekit_sdk_imported", policy_patch.get("livekit_sdk_imported"), False)
    _expect("guarded_start_policy_patch_review_contract.provider_calls_made", policy_patch.get("provider_calls_made"), False)
    _expect("guarded_start_policy_patch_review_contract.tool_calls_made", policy_patch.get("tool_calls_made"), False)
    _expect("guarded_start_policy_patch_review_contract.raw_audio_touched", policy_patch.get("raw_audio_touched"), False)

    human_review = _expect_mapping("guarded_start_human_review_contract", payload.get("guarded_start_human_review_contract"))
    _expect("guarded_start_human_review_contract.schema_version", human_review.get("schema_version"), "atlas.voice_realtime.guarded_start_human_review_contract.v1")
    _expect("guarded_start_human_review_contract.guarded_start_human_review_contract_implemented", human_review.get("guarded_start_human_review_contract_implemented"), True)
    _expect("guarded_start_human_review_contract.human_review_contract_only", human_review.get("human_review_contract_only"), True)
    _expect("guarded_start_human_review_contract.guarded_start_executor_enabled", human_review.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_human_review_contract.guarded_start_executor_implemented", human_review.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_human_review_contract.final_start_executor_enabled", human_review.get("final_start_executor_enabled"), False)
    _expect("guarded_start_human_review_contract.runtime_policy_start_enabled", human_review.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_human_review_contract.real_start_adapter_enabled", human_review.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_human_review_contract.start_execution_allowed", human_review.get("start_execution_allowed"), False)
    _expect("guarded_start_human_review_contract.real_subprocess_start_implemented", human_review.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_human_review_contract.process_launch_attempted", human_review.get("process_launch_attempted"), False)
    _expect("guarded_start_human_review_contract.daemon_started", human_review.get("daemon_started"), False)
    _expect("guarded_start_human_review_contract.process_launch_allowed", human_review.get("process_launch_allowed"), False)
    _expect("guarded_start_human_review_contract.subprocess_module_imported", human_review.get("subprocess_module_imported"), False)
    _expect("guarded_start_human_review_contract.livekit_sdk_imported", human_review.get("livekit_sdk_imported"), False)
    _expect("guarded_start_human_review_contract.provider_calls_made", human_review.get("provider_calls_made"), False)
    _expect("guarded_start_human_review_contract.tool_calls_made", human_review.get("tool_calls_made"), False)
    _expect("guarded_start_human_review_contract.raw_audio_touched", human_review.get("raw_audio_touched"), False)

    final_enablement = _expect_mapping("guarded_start_final_enablement_gate", payload.get("guarded_start_final_enablement_gate"))
    _expect("guarded_start_final_enablement_gate.schema_version", final_enablement.get("schema_version"), "atlas.voice_realtime.guarded_start_final_enablement_gate.v1")
    _expect("guarded_start_final_enablement_gate.guarded_start_final_enablement_gate_implemented", final_enablement.get("guarded_start_final_enablement_gate_implemented"), True)
    _expect("guarded_start_final_enablement_gate.final_enablement_gate_only", final_enablement.get("final_enablement_gate_only"), True)
    _expect("guarded_start_final_enablement_gate.guarded_start_executor_enabled", final_enablement.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_final_enablement_gate.guarded_start_executor_implemented", final_enablement.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_final_enablement_gate.final_start_executor_enabled", final_enablement.get("final_start_executor_enabled"), False)
    _expect("guarded_start_final_enablement_gate.runtime_policy_start_enabled", final_enablement.get("runtime_policy_start_enabled"), False)
    _expect("guarded_start_final_enablement_gate.real_start_adapter_enabled", final_enablement.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_final_enablement_gate.start_execution_allowed", final_enablement.get("start_execution_allowed"), False)
    _expect("guarded_start_final_enablement_gate.real_subprocess_start_implemented", final_enablement.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_final_enablement_gate.process_launch_attempted", final_enablement.get("process_launch_attempted"), False)
    _expect("guarded_start_final_enablement_gate.daemon_started", final_enablement.get("daemon_started"), False)
    _expect("guarded_start_final_enablement_gate.process_launch_allowed", final_enablement.get("process_launch_allowed"), False)
    _expect("guarded_start_final_enablement_gate.subprocess_module_imported", final_enablement.get("subprocess_module_imported"), False)
    _expect("guarded_start_final_enablement_gate.livekit_sdk_imported", final_enablement.get("livekit_sdk_imported"), False)
    _expect("guarded_start_final_enablement_gate.provider_calls_made", final_enablement.get("provider_calls_made"), False)
    _expect("guarded_start_final_enablement_gate.tool_calls_made", final_enablement.get("tool_calls_made"), False)
    _expect("guarded_start_final_enablement_gate.raw_audio_touched", final_enablement.get("raw_audio_touched"), False)

    policy_enablement = _expect_mapping("guarded_start_policy_enablement_contract", payload.get("guarded_start_policy_enablement_contract"))
    _expect("guarded_start_policy_enablement_contract.schema_version", policy_enablement.get("schema_version"), "atlas.voice_realtime.guarded_start_policy_enablement_contract.v1")
    _expect("guarded_start_policy_enablement_contract.guarded_start_policy_enablement_contract_implemented", policy_enablement.get("guarded_start_policy_enablement_contract_implemented"), True)
    _expect("guarded_start_policy_enablement_contract.policy_enablement_contract_only", policy_enablement.get("policy_enablement_contract_only"), True)
    _expect("guarded_start_policy_enablement_contract.guarded_start_executor_enabled", policy_enablement.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_policy_enablement_contract.guarded_start_executor_implemented", policy_enablement.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_policy_enablement_contract.final_start_executor_enabled", policy_enablement.get("final_start_executor_enabled"), False)
    _expect(
        "guarded_start_policy_enablement_contract.runtime_policy_start_enabled",
        policy_enablement.get("runtime_policy_start_enabled"),
        policy_enablement.get("status") == "ready_for_guarded_start_activation_contract",
    )
    _expect("guarded_start_policy_enablement_contract.real_start_adapter_enabled", policy_enablement.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_policy_enablement_contract.start_execution_allowed", policy_enablement.get("start_execution_allowed"), False)
    _expect("guarded_start_policy_enablement_contract.real_subprocess_start_implemented", policy_enablement.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_policy_enablement_contract.process_launch_attempted", policy_enablement.get("process_launch_attempted"), False)
    _expect("guarded_start_policy_enablement_contract.daemon_started", policy_enablement.get("daemon_started"), False)
    _expect("guarded_start_policy_enablement_contract.process_launch_allowed", policy_enablement.get("process_launch_allowed"), False)
    _expect("guarded_start_policy_enablement_contract.subprocess_module_imported", policy_enablement.get("subprocess_module_imported"), False)
    _expect("guarded_start_policy_enablement_contract.livekit_sdk_imported", policy_enablement.get("livekit_sdk_imported"), False)
    _expect("guarded_start_policy_enablement_contract.provider_calls_made", policy_enablement.get("provider_calls_made"), False)
    _expect("guarded_start_policy_enablement_contract.tool_calls_made", policy_enablement.get("tool_calls_made"), False)
    _expect("guarded_start_policy_enablement_contract.raw_audio_touched", policy_enablement.get("raw_audio_touched"), False)

    activation_contract = _expect_mapping("guarded_start_activation_contract", payload.get("guarded_start_activation_contract"))
    _expect("guarded_start_activation_contract.schema_version", activation_contract.get("schema_version"), "atlas.voice_realtime.guarded_start_activation_contract.v1")
    _expect("guarded_start_activation_contract.guarded_start_activation_contract_implemented", activation_contract.get("guarded_start_activation_contract_implemented"), True)
    _expect("guarded_start_activation_contract.activation_contract_only", activation_contract.get("activation_contract_only"), True)
    _expect("guarded_start_activation_contract.guarded_start_executor_enabled", activation_contract.get("guarded_start_executor_enabled"), False)
    _expect("guarded_start_activation_contract.guarded_start_executor_implemented", activation_contract.get("guarded_start_executor_implemented"), False)
    _expect("guarded_start_activation_contract.final_start_executor_enabled", activation_contract.get("final_start_executor_enabled"), False)
    _expect(
        "guarded_start_activation_contract.runtime_policy_start_enabled",
        activation_contract.get("runtime_policy_start_enabled"),
        activation_contract.get("status") == "ready_for_guarded_start_execution_attempt_contract",
    )
    _expect("guarded_start_activation_contract.real_start_adapter_enabled", activation_contract.get("real_start_adapter_enabled"), False)
    _expect("guarded_start_activation_contract.start_execution_allowed", activation_contract.get("start_execution_allowed"), False)
    _expect("guarded_start_activation_contract.real_subprocess_start_implemented", activation_contract.get("real_subprocess_start_implemented"), False)
    _expect("guarded_start_activation_contract.process_launch_attempted", activation_contract.get("process_launch_attempted"), False)
    _expect("guarded_start_activation_contract.daemon_started", activation_contract.get("daemon_started"), False)
    _expect("guarded_start_activation_contract.process_launch_allowed", activation_contract.get("process_launch_allowed"), False)
    _expect("guarded_start_activation_contract.subprocess_module_imported", activation_contract.get("subprocess_module_imported"), False)
    _expect("guarded_start_activation_contract.livekit_sdk_imported", activation_contract.get("livekit_sdk_imported"), False)
    _expect("guarded_start_activation_contract.provider_calls_made", activation_contract.get("provider_calls_made"), False)
    _expect("guarded_start_activation_contract.tool_calls_made", activation_contract.get("tool_calls_made"), False)
    _expect("guarded_start_activation_contract.raw_audio_touched", activation_contract.get("raw_audio_touched"), False)

    start_attempt = _expect_mapping("start_attempt", payload.get("start_attempt"))
    _expect("start_attempt.process_launch_attempted", start_attempt.get("process_launch_attempted"), False)
    _expect("start_attempt.daemon_started", start_attempt.get("daemon_started"), False)
    _expect("start_attempt.launch_allowed", start_attempt.get("launch_allowed"), False)
    _expect("start_attempt.decision_receipt_required", start_attempt.get("decision_receipt_required"), True)

    return payload


def _expect(path: str, actual: Any, expected: Any) -> None:
    if actual != expected:
        raise SupervisedProcessAdapterPacketViolation(f"{path} expected {expected!r}, got {actual!r}")


def _expect_mapping(path: str, value: Any) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise SupervisedProcessAdapterPacketViolation(f"{path} must be an object")

    return value
