<?php

namespace Tests\Feature\Ai;

use App\Services\Ai\Kernel\Architecture\AtlasAiArchitectureValidationService;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class AtlasAiArchitectureValidateCommandTest extends TestCase
{
    public function test_command_validates_architecture_contracts_as_json(): void
    {
        $exit = Artisan::call('atlas:ai:architecture-validate', [
            '--json' => true,
        ]);

        $payload = json_decode(Artisan::output(), true, flags: JSON_THROW_ON_ERROR);

        $this->assertSame(0, $exit);
        $this->assertSame('ok', $payload['status']);
        $this->assertTrue(data_get($payload, 'kernel.valid'));
        $this->assertTrue(data_get($payload, 'kernel.surface_adapter_contract'));
        $this->assertTrue(data_get($payload, 'kernel.provider_driver_contract'));
        $this->assertTrue(data_get($payload, 'kernel.failure_domains.valid'));
        $this->assertGreaterThanOrEqual(30, data_get($payload, 'kernel.failure_domains.count'));
        $this->assertSame([], data_get($payload, 'kernel.failure_domains.missing_handlers'));
        $this->assertTrue(data_get($payload, 'kernel.failure_classifier.valid'));
        $this->assertGreaterThanOrEqual(30, data_get($payload, 'kernel.failure_classifier.rule_count'));
        $this->assertGreaterThanOrEqual(8, data_get($payload, 'kernel.failure_classifier.status_code_count'));
        $this->assertSame([], data_get($payload, 'kernel.failure_classifier.missing_domains'));
        $this->assertSame([], data_get($payload, 'kernel.failure_classifier.duplicate_signals'));
        $this->assertTrue(data_get($payload, 'kernel.slo_targets.valid'));
        $this->assertGreaterThanOrEqual(14, data_get($payload, 'kernel.slo_targets.count'));
        $this->assertSame('atlas.kernel.slo_target.v1', data_get($payload, 'kernel.slo_targets.schema_version'));
        $this->assertContains('decide.issue', data_get($payload, 'kernel.slo_targets.stages'));
        $this->assertContains('ledger.append', data_get($payload, 'kernel.slo_targets.stages'));
        $this->assertSame([], data_get($payload, 'kernel.slo_targets.errors'));
        $this->assertTrue(data_get($payload, 'kernel.surface_adapters.valid'));
        $this->assertGreaterThanOrEqual(8, data_get($payload, 'kernel.surface_adapters.count'));
        $this->assertContains('atlas_cli_dev', data_get($payload, 'kernel.surface_adapters.surfaces'));
        $this->assertContains('atlas_worker', data_get($payload, 'kernel.surface_adapters.surfaces'));
        $this->assertContains('atlas_mcp_readonly', data_get($payload, 'kernel.surface_adapters.surfaces'));
        $this->assertContains('atlas_vault', data_get($payload, 'kernel.surface_adapters.surfaces'));
        $this->assertSame('atlas_cli_chat', data_get($payload, 'kernel.surface_adapters.aliases.atlas_ask'));
        $this->assertSame('atlas_cli_dev', data_get($payload, 'kernel.surface_adapters.aliases.atlas_cli_continue'));
        $this->assertSame([], data_get($payload, 'kernel.surface_adapters.errors'));
        $this->assertTrue(data_get($payload, 'kernel.provider_drivers.valid'));
        $this->assertGreaterThanOrEqual(4, data_get($payload, 'kernel.provider_drivers.count'));
        $this->assertContains('codex_cli', data_get($payload, 'kernel.provider_drivers.providers'));
        $this->assertContains('claude_codex', data_get($payload, 'kernel.provider_drivers.providers'));
        $this->assertSame([], data_get($payload, 'kernel.provider_drivers.errors'));
        $this->assertIsArray(data_get($payload, 'kernel.provider_drivers.warnings'));
        $this->assertTrue(data_get($payload, 'kernel.ledger_projections.valid'));
        $this->assertSame('atlas.ledger_projection_registry.v1', data_get($payload, 'kernel.ledger_projections.schema_version'));
        $this->assertSame(3, data_get($payload, 'kernel.ledger_projections.count'));
        $this->assertContains('ai_traces', data_get($payload, 'kernel.ledger_projections.projection_ids'));
        $this->assertContains('atlas_engineering_runs', data_get($payload, 'kernel.ledger_projections.projection_ids'));
        $this->assertContains('atlas_tool_runs', data_get($payload, 'kernel.ledger_projections.projection_ids'));
        $this->assertSame('atlas.ledger_projection_drift.v1', data_get($payload, 'kernel.ledger_projections.drift.schema_version'));
        $this->assertIsBool(data_get($payload, 'kernel.ledger_projections.drift.available'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.valid'));
        $this->assertGreaterThanOrEqual(30, data_get($payload, 'kernel.static_scan.summary.total_count'));
        $this->assertSame(
            data_get($payload, 'kernel.static_scan.summary.total_count'),
            data_get($payload, 'kernel.static_scan.summary.passed_count')
        );
        $this->assertSame(0, data_get($payload, 'kernel.static_scan.summary.failed_count'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.summary.failed_keys'));
        $this->assertSame(0, data_get($payload, 'kernel.static_scan.summary.violation_count'));
        $this->assertTrue(data_get($payload, 'documentation.valid'));
        $this->assertSame('ok', data_get($payload, 'documentation.status'));
        $this->assertSame(0, data_get($payload, 'documentation.summary.required_missing_count'));
        $this->assertSame(0, data_get($payload, 'documentation.summary.frontmatter_violation_count'));
        $this->assertContains(
            'docs/engineering-knowledge-base/atlas-ai-session-bootstrap.md',
            collect(data_get($payload, 'documentation.required_docs', []))->pluck('path')->all(),
        );
        $this->assertContains(
            'docs/engineering-knowledge-base/atlas-ai-runtime-language-boundaries.md',
            collect(data_get($payload, 'documentation.required_docs', []))->pluck('path')->all(),
        );
        $this->assertContains(
            'docs/engineering-knowledge-base/atlas-ai-kernel-architecture.md',
            collect(data_get($payload, 'documentation.oversized_docs', []))->pluck('path')->all(),
        );
        $this->assertContains('ap36_kernel_pipeline_health_read_model', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap37_architecture_validation_surface', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap38_architecture_validation_observability', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap39_architecture_validation_contract_parity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap40_architecture_validation_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap41_self_improvement_architecture_validation_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap42_self_improvement_architecture_audit_schedule', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap43_self_improvement_flow_cadence_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap44_self_improvement_command_next_run_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap45_self_improvement_schedule_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap46_self_improvement_schedule_health_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap47_self_improvement_schedule_health_ledger_event', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap48_self_improvement_schedule_replay_read_model', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap49_self_improvement_schedule_replay_surfaces', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap50_self_improvement_schedule_replay_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap51_self_improvement_schedule_replay_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap52_self_improvement_schedule_replay_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap53_self_improvement_schedule_replay_review_signal_surfaces', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap54_kernel_pipeline_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap55_repair_loop_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap56_slo_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap57_slo_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap58_kernel_pipeline_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap59_repair_loop_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap60_repair_loop_unavailable_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap61_slo_unavailable_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap62_mcp_replay_unavailable_review_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap63_schedule_replay_unavailable_shape_parity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap64_mcp_replay_window_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap65_mcp_replay_filter_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap66_replay_report_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap67_observability_replay_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap68_replay_report_validation_limit_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap69_self_improvement_runtime_window_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap70_self_improvement_schedule_window_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap71_self_improvement_orchestrator_window_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap72_telemetry_window_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap73_runtime_budget_window_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap74_ledger_envelope_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap75_ledger_envelope_report_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap76_telemetry_list_limit_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap77_programming_iteration_policy_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap78_open_brain_mcp_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap79_memory_query_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap80_provider_projection_audit_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap81_conversation_context_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap82_retrieval_rank_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap83_atlas_vault_command_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap84_memory_recall_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap85_context_pack_memory_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap86_semantic_context_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap87_provider_projection_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap88_test_command_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap89_engineering_harness_runner_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap90_engineering_harnessability_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap91_engineering_docker_harness_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap92_engineering_test_matrix_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap93_engineering_claude_code_baseline_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap94_engineering_benchmark_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap95_engineering_context_intelligence_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap96_cli_limit_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap97_scheduler_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap98_self_improvement_input_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap99_provider_usage_performance_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap100_context_pack_manifest_reflection_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap101_context_retrieval_router_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap102_open_brain_retrieval_plan_summary_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap103_retrieval_required_source_availability_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap104_retrieval_review_signal_next_action_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap105_open_brain_retrieval_self_improvement_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap106_learning_proposed_review_signal_projection_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap107_proposal_inbox_review_signal_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap108_learning_proposed_inbox_link_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap109_operation_completed_inbox_refs_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap110_schedule_replay_inbox_refs_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap111_schedule_replay_inbox_refs_surface_parity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap112_schedule_replay_inbox_item_hydration', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap113_schedule_replay_inbox_item_hydration_surface_parity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap114_schedule_replay_inbox_hydration_gap_signal', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap115_self_improvement_schedule_replay_inbox_gap_finding', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap116_self_improvement_schedule_replay_inbox_gap_emission', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap117_proposal_inbox_review_signal_severity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap118_proposal_review_action_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap119_cli_inbox_review_action_result_parity', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap120_inbox_action_evidence_ledger_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap121_inbox_action_replay_read_model', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap122_inbox_action_mcp_report', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap123_self_improvement_inbox_action_replay_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap124_observability_inbox_action_replay', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap125_inbox_action_report_surfaces', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap126_architecture_validate_post_ap98_human_output', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap127_cli_help_architecture_operations_discovery', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap128_architecture_operations_shared_catalog', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap129_architecture_operations_mcp_tool', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap130_architecture_operations_direct_surfaces', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap131_self_improvement_architecture_operations_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap132_architecture_operations_metadata_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap133_architecture_operations_filter_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap134_decision_receipt_hash_runtime_guard', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap135_decision_receipt_determinism_test', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap136_decision_receipt_chain_replay', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap137_decision_receipt_replay_surfaces', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap138_decision_receipt_replay_curator_review', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap139_decision_receipt_replay_inbox_emission', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap140_ledger_replay_command_surface', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap141_ledger_projection_registry_contract', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap142_ledger_projection_inbox_action', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertContains('ap143_ledger_projection_curator_action_emission', data_get($payload, 'kernel.static_scan.summary.valid_keys'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap1_surface_provider_bypass.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap2_surface_context_bypass.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap6_decision_receipt_propagation.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap13_decision_receipt_runtime_guard.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap134_decision_receipt_hash_runtime_guard.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap135_decision_receipt_determinism_test.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap136_decision_receipt_chain_replay.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap12_provider_driver_identity_bypass.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap14_tool_tier_hot_path.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap15_provider_memory_privacy.violations'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap16_slo_observability.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap17_kernel_pipeline_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap17_kernel_pipeline_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap18_repair_loop_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap18_repair_loop_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap19_mcp_domain_catalog_parity.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap19_mcp_domain_catalog_parity.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap20_cli_fix_dev_repair_alias.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap20_cli_fix_dev_repair_alias.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap21_cli_continue_dev_resume_alias.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap21_cli_continue_dev_resume_alias.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap22_cli_forge_programming_harness_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap22_cli_forge_programming_harness_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap23_chat_dev_programming_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap23_chat_dev_programming_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap24_surface_alias_canonicalization.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap24_surface_alias_canonicalization.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap25_decide_model_selection_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap25_decide_model_selection_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap26_cli_dev_model_selection_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap26_cli_dev_model_selection_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap27_chat_model_selection_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap27_chat_model_selection_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap28_kernel_model_selection_contract_factory.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap28_kernel_model_selection_contract_factory.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap29_programming_surface_contract_factory.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap29_programming_surface_contract_factory.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap30_chat_programming_contract_factory.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap30_chat_programming_contract_factory.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap31_continue_resume_contract_factory.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap31_continue_resume_contract_factory.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap32_fix_contract_factory.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap32_fix_contract_factory.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap36_kernel_pipeline_health_read_model.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap36_kernel_pipeline_health_read_model.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap37_architecture_validation_surface.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap37_architecture_validation_surface.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap38_architecture_validation_observability.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap38_architecture_validation_observability.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap39_architecture_validation_contract_parity.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap39_architecture_validation_contract_parity.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap40_architecture_validation_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap40_architecture_validation_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap41_self_improvement_architecture_validation_review.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap41_self_improvement_architecture_validation_review.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap42_self_improvement_architecture_audit_schedule.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap42_self_improvement_architecture_audit_schedule.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap43_self_improvement_flow_cadence_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap43_self_improvement_flow_cadence_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap44_self_improvement_command_next_run_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap44_self_improvement_command_next_run_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap45_self_improvement_schedule_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap45_self_improvement_schedule_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap46_self_improvement_schedule_health_review.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap46_self_improvement_schedule_health_review.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap47_self_improvement_schedule_health_ledger_event.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap47_self_improvement_schedule_health_ledger_event.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap48_self_improvement_schedule_replay_read_model.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap48_self_improvement_schedule_replay_read_model.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap49_self_improvement_schedule_replay_surfaces.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap49_self_improvement_schedule_replay_surfaces.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap50_self_improvement_schedule_replay_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap50_self_improvement_schedule_replay_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap51_self_improvement_schedule_replay_review.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap51_self_improvement_schedule_replay_review.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap52_self_improvement_schedule_replay_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap52_self_improvement_schedule_replay_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap53_self_improvement_schedule_replay_review_signal_surfaces.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap53_self_improvement_schedule_replay_review_signal_surfaces.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap54_kernel_pipeline_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap54_kernel_pipeline_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap55_repair_loop_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap55_repair_loop_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap56_slo_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap56_slo_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap57_slo_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap57_slo_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap58_kernel_pipeline_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap58_kernel_pipeline_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap59_repair_loop_mcp_tool.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap59_repair_loop_mcp_tool.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap60_repair_loop_unavailable_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap60_repair_loop_unavailable_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap61_slo_unavailable_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap61_slo_unavailable_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap62_mcp_replay_unavailable_review_signal.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap62_mcp_replay_unavailable_review_signal.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap63_schedule_replay_unavailable_shape_parity.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap63_schedule_replay_unavailable_shape_parity.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap64_mcp_replay_window_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap64_mcp_replay_window_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap65_mcp_replay_filter_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap65_mcp_replay_filter_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap66_replay_report_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap66_replay_report_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap67_observability_replay_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap67_observability_replay_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap68_replay_report_validation_limit_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap68_replay_report_validation_limit_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap69_self_improvement_runtime_window_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap69_self_improvement_runtime_window_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap70_self_improvement_schedule_window_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap70_self_improvement_schedule_window_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap71_self_improvement_orchestrator_window_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap71_self_improvement_orchestrator_window_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap72_telemetry_window_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap72_telemetry_window_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap73_runtime_budget_window_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap73_runtime_budget_window_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap74_ledger_envelope_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap74_ledger_envelope_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap75_ledger_envelope_report_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap75_ledger_envelope_report_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap76_telemetry_list_limit_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap76_telemetry_list_limit_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap77_programming_iteration_policy_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap77_programming_iteration_policy_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap78_open_brain_mcp_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap78_open_brain_mcp_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap79_memory_query_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap79_memory_query_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap80_provider_projection_audit_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap80_provider_projection_audit_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap81_conversation_context_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap81_conversation_context_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap82_retrieval_rank_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap82_retrieval_rank_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap83_atlas_vault_command_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap83_atlas_vault_command_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap84_memory_recall_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap84_memory_recall_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap85_context_pack_memory_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap85_context_pack_memory_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap86_semantic_context_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap86_semantic_context_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap87_provider_projection_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap87_provider_projection_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap88_test_command_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap88_test_command_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap89_engineering_harness_runner_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap89_engineering_harness_runner_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap90_engineering_harnessability_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap90_engineering_harnessability_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap91_engineering_docker_harness_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap91_engineering_docker_harness_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap92_engineering_test_matrix_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap92_engineering_test_matrix_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap93_engineering_claude_code_baseline_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap93_engineering_claude_code_baseline_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap94_engineering_benchmark_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap94_engineering_benchmark_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap95_engineering_context_intelligence_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap95_engineering_context_intelligence_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap96_cli_limit_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap96_cli_limit_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap97_scheduler_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap97_scheduler_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap98_self_improvement_input_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap98_self_improvement_input_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap99_provider_usage_performance_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap99_provider_usage_performance_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap100_context_pack_manifest_reflection_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap100_context_pack_manifest_reflection_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap101_context_retrieval_router_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap101_context_retrieval_router_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap102_open_brain_retrieval_plan_summary_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap102_open_brain_retrieval_plan_summary_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap103_retrieval_required_source_availability_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap103_retrieval_required_source_availability_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap104_retrieval_review_signal_next_action_contract.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap104_retrieval_review_signal_next_action_contract.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap33_surface_capability_parity.valid'));
        $this->assertGreaterThanOrEqual(39, data_get($payload, 'kernel.static_scan.ap33_surface_capability_parity.checked'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap33_surface_capability_parity.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap34_capability_surface_coverage.valid'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap34_capability_surface_coverage.violations'));
        $this->assertTrue(data_get($payload, 'kernel.static_scan.ap35_surface_adapter_parity_map_coverage.valid'));
        $this->assertContains('atlas_cli_dev', data_get($payload, 'kernel.static_scan.ap35_surface_adapter_parity_map_coverage.mapped_adapters'));
        $this->assertContains('atlas_vault', data_get($payload, 'kernel.static_scan.ap35_surface_adapter_parity_map_coverage.mapped_adapters'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap35_surface_adapter_parity_map_coverage.unmapped_adapters'));
        $this->assertSame([], data_get($payload, 'kernel.static_scan.ap35_surface_adapter_parity_map_coverage.violations'));
        $this->assertTrue(data_get($payload, 'capabilities.valid'));
        $this->assertTrue(data_get($payload, 'capabilities.surface_coverage.valid'));
        $this->assertSame([], data_get($payload, 'capabilities.surface_coverage.errors'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'capabilities.count'));
        $this->assertTrue(data_get($payload, 'capabilities.surface_adapter_parity.valid'));
        $this->assertGreaterThanOrEqual(39, data_get($payload, 'capabilities.surface_adapter_parity.checked'));
        $this->assertSame([], data_get($payload, 'capabilities.surface_adapter_parity.errors'));
        $this->assertSame([], data_get($payload, 'capabilities.surface_adapter_parity.skipped'));
        $this->assertSame([], data_get($payload, 'capabilities.surface_adapter_parity.unmapped_adapters'));
        $this->assertTrue(data_get($payload, 'orchestrators.valid'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'orchestrators.count'));
        $this->assertTrue(data_get($payload, 'domains.valid'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'domains.domain_count'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'domains.flow_count'));
        $this->assertGreaterThanOrEqual(3, data_get($payload, 'onboarding.ready_domains'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'onboarding.scaffold_domains'));
        $this->assertSame(
            data_get($payload, 'onboarding.domain_count'),
            array_sum(data_get($payload, 'onboarding.status_counts'))
        );
        $this->assertSame(0, data_get($payload, 'onboarding.executable_incomplete_domains'));
        $this->assertGreaterThanOrEqual(1, data_get($payload, 'onboarding.domain_count'));
    }

    public function test_human_output_renders_post_ap98_static_scan_violations(): void
    {
        $payload = app(AtlasAiArchitectureValidationService::class)->payload();
        data_set($payload, 'status', 'failed');
        data_set($payload, 'kernel.valid', false);
        data_set($payload, 'kernel.static_scan.valid', false);
        data_set($payload, 'kernel.static_scan.ap125_inbox_action_report_surfaces.valid', false);
        data_set($payload, 'kernel.static_scan.ap125_inbox_action_report_surfaces.violations', [
            'AP-125 synthetic violation for human output',
        ]);
        data_set($payload, 'kernel.static_scan.summary.failed_count', 1);
        data_set($payload, 'kernel.static_scan.summary.failed_keys', ['ap125_inbox_action_report_surfaces']);
        data_set($payload, 'kernel.static_scan.summary.violation_count', 1);

        $this->mock(AtlasAiArchitectureValidationService::class, function ($mock) use ($payload): void {
            $mock->shouldReceive('payload')->once()->andReturn($payload);
        });

        $exit = Artisan::call('atlas:ai:architecture-validate');
        $output = Artisan::output();

        $this->assertSame(1, $exit);
        $this->assertStringContainsString('[kernel.static.ap125_inbox_action_report_surfaces]', $output);
        $this->assertStringContainsString('AP-125 synthetic violation for human output', $output);
    }
}
