<?php

declare(strict_types=1);

namespace App\Services\Ai\SoftwareCompanyStewardship\AreaFocusLoop\DeepFinding;

use App\Services\Ai\SoftwareCompanyStewardship\AreaFocusLoop\AreaFocusDeepFindingEngineService;

/**
 * Strategic multiplier seed catalogue — extracted verbatim from
 * AreaFocusDeepFindingEngineService by the GOD-DEBULK split.
 *
 * Highest-leverage roadmap order for the loop. These are not free-form docs:
 * each seed points at an existing runtime file + focused test path so AP-790
 * can turn the idea into a bounded Dev/Forge improvement. Consumed only by the
 * façade's strategicMultiplierBacklog(); taxonomy constants live on the façade.
 *
 * @see AreaFocusDeepFindingEngineService::strategicMultiplierBacklog()
 */
class StrategicMultiplierSeeds
{
    /**
     * @var list<array{id:string,title:string,detail:string,source:string,test:string,owner:string,kind:string,severity:string,tier:string,jump:string,attention:string}>
     */
    public const ALL = [
        [
            'id' => 's3_decide_upstream_every_packet',
            'title' => 'Make Atlas Decide upstream mandatory for owner execution packets',
            'detail' => 'Route every autonomous Dev/Forge packet through provider/topology choice before owner execution so Cursor, Codex, Claude, Gemini or another real provider can be swapped by policy instead of hardcoded loops.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/AreaFocusLoop/AutonomousEvolutionSessionService.php',
            'test' => 'AutonomousEvolutionSessionServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_ATLAS_DEV,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'S3',
            'jump' => 'Provider antifragility: one provider hitting limit should not stop the factory loop.',
            'attention' => 'Must use real AtlasDecide/provider receipts; no mock topology in runtime.',
        ],
        [
            'id' => 's4_reliable_24h_loop_recovery',
            'title' => 'Strengthen 24h stewardship recovery until consecutive merged cycles are normal',
            'detail' => 'Improve reliable loop resume, blocker quarantine, candidate refill and merge continuation so AP-790 keeps cycling after blocked or provider-timeout runs.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/AreaFocusLoop/Reliable24hLoopRunnerService.php',
            'test' => 'Reliable24hLoopRunnerServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_ATLAS_DEV,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'S4',
            'jump' => 'Turns the loop from demo cycles into a day-long software factory runner.',
            'attention' => 'Must count only ledger outcome=merged and merge_performed=true.',
        ],
        [
            'id' => 's1_compounding_learning_feedback',
            'title' => 'Close P16 learning feedback into next-cycle defaults',
            'detail' => 'Feed learning capsules and owner runtime outcomes back into priority, topology, validation and prompt defaults so every successful cycle improves the next one.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/AreaFocusLoop/StewardshipPriorityEngineService.php',
            'test' => 'StewardshipPriorityEngineServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPROVEMENT,
            'severity' => 'high',
            'tier' => 'S1',
            'jump' => 'Compounding: the same class of work should get cheaper and safer over time.',
            'attention' => 'Must record evidence refs and avoid hidden prompt drift.',
        ],
        [
            'id' => 's2_self_construction_default_for_atlas',
            'title' => 'Route Atlas-on-Atlas gaps through Self-Construction by default',
            'detail' => 'When the selected area is Atlas itself, convert validated gaps into governed Self-Construction packets instead of loose provider tasks.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/AreaFocusLoop/AutonomousEvolutionSessionService.php',
            'test' => 'AutonomousEvolutionSessionServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_ATLAS_DEV,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'S2',
            'jump' => 'Atlas becomes its own governed build queue, not a collection of ad-hoc provider calls.',
            'attention' => 'Must preserve allowed_files, branch sandbox and owner receipts.',
        ],
        [
            'id' => 'm1_architect_agent_spec_pack',
            'title' => 'Introduce Architect-agent spec pack gate for R4 autonomous work',
            'detail' => 'Before high-risk autonomous work executes, require a spec pack with acceptance, rollback and breaking-change matrix generated by the architecture lane.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/DepartmentContractRuntime.php',
            'test' => 'DepartmentContractRuntimeTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'M1',
            'jump' => 'Lets the loop eat larger engineering work without turning the operator into the spec writer.',
            'attention' => 'Do not allow R5/professional-risk work without operator signature.',
        ],
        [
            'id' => 'm5_quality_bar_auto_block',
            'title' => 'Wire quality-bar telemetry as an auto-blocking immune gate',
            'detail' => 'Turn quality-bar breaches into machine blockers that pause the loop before degraded work accumulates.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/AtlasUniversalGatesEvaluator.php',
            'test' => 'AtlasUniversalGatesEvaluatorTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'M5',
            'jump' => 'Prevents silent quality drift during 24h/24-7 autonomous operation.',
            'attention' => 'Must emit gate evidence, not boolean-only pass/fail.',
        ],
        [
            'id' => 'm6_unified_evidence_replay_refs',
            'title' => 'Unify Dev, Forge and Stewardship evidence refs for replay',
            'detail' => 'Bridge local Dev receipts, Forge evidence and Stewardship cycle receipts into replayable evidence refs.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/StewardshipEvolution/StewardshipOwnerRuntimeResultBridgeService.php',
            'test' => 'StewardshipOwnerRuntimeResultBridgeServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_EVIDENCE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'M6',
            'jump' => 'Makes a full night/day of work auditable as a deterministic timeline.',
            'attention' => 'Must not claim replay completeness without concrete receipt paths.',
        ],
        [
            'id' => 's5_cross_department_choreography_runtime',
            'title' => 'Materialize cross-department choreography for Dev/Forge repair loops',
            'detail' => 'Route security, review, QA and architecture veto/repair signals through the cross-department handoff state machine instead of isolated blockers.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/RunbookOrchestrator.php',
            'test' => 'RunbookOrchestratorTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'S5',
            'jump' => 'Turns 11 departments into a coordinated runtime instead of separate services.',
            'attention' => 'Repair loop must stay bounded and veto propagation must be explicit.',
        ],
        [
            'id' => 'a3_mission_control_loop_visibility',
            'title' => 'Make Mission Control show live stewardship loop state',
            'detail' => 'Expose phases, blockers, evidence, branch, inbox and merge status for current area-focus cycles in Mission Control.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/AtlasMissionControlCockpitService.php',
            'test' => 'AtlasMissionControlCockpitServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_PRODUCT_MODE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'A3',
            'jump' => 'Lets one operator govern autonomous engineering at a glance.',
            'attention' => 'Surface must project receipts; it must not become a parallel source of truth.',
        ],
        [
            'id' => 'a2_universal_gates_single_evaluator',
            'title' => 'Consolidate universal gate runs into a single evaluator receipt',
            'detail' => 'Make all AP-790 owner cycles pass through a canonical gate-run report with blockers, evidence refs and repair hints.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/AtlasUniversalGatesEvaluator.php',
            'test' => 'AtlasUniversalGatesEvaluatorTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'A2',
            'jump' => 'Converts scattered quality checks into an immune system.',
            'attention' => 'Do not mark skipped phases green without signed skip reason.',
        ],
        [
            'id' => 'e1_context_twin_evolution_preflight',
            'title' => 'Require APCR plus Software Twin plus Verified Evolution before every code mutation',
            'detail' => 'Combine persistent context, software twin reality and verified evolution boundary before any owner flow writes code.',
            'source' => 'app/Services/Ai/SoftwareCompanyStewardship/AreaFocusLoop/AutonomousEvolutionSessionService.php',
            'test' => 'AutonomousEvolutionSessionServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_ATLAS_DEV,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E1',
            'jump' => 'Eliminates session-zero, stale-context and wrong-boundary writes before they happen.',
            'attention' => 'Must remain a preflight gate; never hide it as provider prompt text.',
        ],
        [
            'id' => 'e2_architecture_evolution_proposal_runtime',
            'title' => 'Let Atlas propose structural redesigns of its own engineering runtime',
            'detail' => 'Promote architecture evolution proposals for phases, departments and gates into bounded reviewable packets.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/RunbookOrchestrator.php',
            'test' => 'RunbookOrchestratorTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E2',
            'jump' => 'Moves Atlas from feature self-construction to governed architectural self-evolution.',
            'attention' => 'Requires replay/regression evidence before any architecture promotion.',
        ],
        [
            'id' => 'e3_reality_sandbox_gate_for_r3_plus',
            'title' => 'Run Reality Sandbox counterfactuals before R3+ autonomous execution',
            'detail' => 'Use AARS and counterfactual simulation to explore outcomes before high-risk Dev/Forge work enters execution.',
            'source' => 'app/Services/Ai/RealitySandbox/AtlasAutonomousRealitySandboxService.php',
            'test' => 'AtlasAutonomousRealitySandboxServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E3',
            'jump' => 'Turns high-risk work from one-shot execution into simulated decision under uncertainty.',
            'attention' => 'Simulation output must be evidence, not authority; operator policy still governs sensitive work.',
        ],
        [
            'id' => 'e4_temporal_4d_replay_for_every_mutation',
            'title' => 'Attach temporal 4D replay references to every autonomous mutation',
            'detail' => 'Make each cycle replayable across context, decision, patch, evidence and learning state.',
            'source' => 'app/Services/Ai/Reality/AtlasUnifiedRealityGraphTemporalService.php',
            'test' => 'AtlasUnifiedRealityGraphTemporalServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_EVIDENCE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E4',
            'jump' => 'Makes long autonomous runs debuggable as timelines instead of opaque commit lists.',
            'attention' => 'No replay completeness claim without concrete receipt paths and hashes.',
        ],
        [
            'id' => 'e5_verified_context_immune_system',
            'title' => 'Make Verified Context Execution an immune gate for AP-790',
            'detail' => 'Block owner execution when context freshness, sufficiency or contradiction checks fail.',
            'source' => 'app/Services/Ai/VerifiedContextExecution/AtlasVerifiedContextExecutionLoopService.php',
            'test' => 'AtlasVerifiedContextExecutionLoopServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E5',
            'jump' => 'Prevents brilliant provider output on stale or incomplete context.',
            'attention' => 'Must expose exact missing context, not generic context_failed.',
        ],
        [
            'id' => 'e6_long_horizon_month_scale_continuity',
            'title' => 'Give long-horizon continuity authority over multi-day autonomous Obras',
            'detail' => 'Thread month-scale state, recovery plans and strategic forgetting into stewardship cycles.',
            'source' => 'app/Services/Ai/LongHorizon/LongHorizonContinuityCertificationService.php',
            'test' => 'LongHorizonContinuityCertificationServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'E6',
            'jump' => 'Lets Atlas carry large Obras over days or weeks without forgetting the shape of the work.',
            'attention' => 'Must distinguish useful forgetting from lost context.',
        ],
        [
            'id' => 'e7_swarm_specialists_per_slice',
            'title' => 'Dispatch specialist swarms per Dev/Forge slice with debate-and-judge',
            'detail' => 'Turn single-owner execution into specialist workcells for architecture, implementation, review, security and repair.',
            'source' => 'app/Services/Ai/AgenticWorkcell/AtlasAgenticWorkcellRuntimeService.php',
            'test' => 'AtlasAgenticWorkcellRuntimeServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'E7',
            'jump' => 'Raises quality by forcing disagreement and specialist coverage before merge.',
            'attention' => 'Must avoid provider fanout without budget and reservation gates.',
        ],
        [
            'id' => 'e8_compounding_l8_distillation_metric',
            'title' => 'Measure and optimize the N x M compounding multiplier directly',
            'detail' => 'Distill learning across runs into measurable factory improvements in cost, quality, repair and provider choice.',
            'source' => 'app/Services/Ai/Compounding/AtlasCompoundingLevel8DistillationService.php',
            'test' => 'AtlasCompoundingLevel8DistillationServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPROVEMENT,
            'severity' => 'medium',
            'tier' => 'E8',
            'jump' => 'Makes every month of Atlas work measurably stronger than the prior month.',
            'attention' => 'Metric must not reward easy cycles over meaningful factory power.',
        ],
        [
            'id' => 'e9_live_cartography_runtime_zoom',
            'title' => 'Expose live universe-to-component cartography for running loops',
            'detail' => 'Project branches, phases, owners, evidence, risks and learning into cartographic views during execution.',
            'source' => 'app/Services/Ai/Cartography/CartographyTruthGuardService.php',
            'test' => 'CartographyTruthGuardServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_PRODUCT_MODE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'E9',
            'jump' => 'Lets the operator see the software factory as a live map rather than terminal noise.',
            'attention' => 'Cartography must derive from receipts; never become decorative state.',
        ],
        [
            'id' => 'e10_cognitive_immune_g0_g8_live',
            'title' => 'Wire cognitive immune checks into autonomous engineering decisions',
            'detail' => 'Detect drift, contradiction, bias, hallucinated authority and scope creep while the factory is operating.',
            'source' => 'app/Services/Ai/Cognition/AtlasCognitionScoreCardService.php',
            'test' => 'AtlasCognitionScoreCardServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'high',
            'tier' => 'E10',
            'jump' => 'Turns cognition failure into a first-class blocker before bad work lands.',
            'attention' => 'Must produce actionable repair hints, not just “low confidence”.',
        ],
        [
            'id' => 'q1_reality_compiler',
            'title' => 'Introduce Reality Compiler slices for intent-to-system execution',
            'detail' => 'Compile human intent into governed AAEOS execution packets that traverse spec, simulation, swarm, evidence and review.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/AutonomousWorkExecutionOs.php',
            'test' => 'AutonomousWorkExecutionOsTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q1',
            'jump' => 'Turns feature creation from ticket choreography into governed compilation.',
            'attention' => 'Cannot bypass the 17-phase AAEOS runbook.',
        ],
        [
            'id' => 'q2_parallel_universes_execution',
            'title' => 'Evaluate best-of-N isolated implementation universes for R3+ work',
            'detail' => 'Run multiple isolated strategies and merge only the judged winner, preserving losing universes as learning evidence.',
            'source' => 'app/Services/Ai/AtlasDecide/AtlasSwarmParallelDispatchService.php',
            'test' => 'AtlasSwarmParallelDispatchServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q2',
            'jump' => 'Quality jumps from one chosen strategy to best-of-N governed execution.',
            'attention' => 'Requires strict worktree isolation and budget caps.',
        ],
        [
            'id' => 'q3_adversarial_self_testing',
            'title' => 'Add adversarial self-testing as a permanent factory lane',
            'detail' => 'Spawn safe adversarial checks that try to break gates, context, sandbox and merge assumptions, then convert failures into tests.',
            'source' => 'app/Services/Ai/AgenticEngineeringOs/AtlasUniversalGatesEvaluator.php',
            'test' => 'AtlasUniversalGatesEvaluatorTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q3',
            'jump' => 'Robustness grows because Atlas continuously attacks its own weak points.',
            'attention' => 'Adversarial probes must be simulated and non-destructive.',
        ],
        [
            'id' => 'q4_probabilistic_programming_layer',
            'title' => 'Attach probability distributions to autonomous engineering decisions',
            'detail' => 'Estimate rollback, success, cost and risk probability for each candidate before execution.',
            'source' => 'app/Services/Ai/StrategicReality/AtlasStrategicRealityRuntimeService.php',
            'test' => 'AtlasStrategicRealityRuntimeServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_AAEOS,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q4',
            'jump' => 'Replaces pass/fail intuition with quantified decision quality.',
            'attention' => 'Probabilities must expose evidence and confidence, not pretend certainty.',
        ],
        [
            'id' => 'q5_code_genome_evolution_engine',
            'title' => 'Model the codebase as an evolvable genome',
            'detail' => 'Identify genes, variants and mutation candidates, then let fitness gates propose better architecture over time.',
            'source' => 'app/Services/Ai/Compounding/AtlasLearningMutationRuntimeService.php',
            'test' => 'AtlasLearningMutationRuntimeServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPROVEMENT,
            'severity' => 'medium',
            'tier' => 'Q5',
            'jump' => 'The codebase improves as an organism instead of only through requested features.',
            'attention' => 'Mutation must be proposal-first until gates prove safety.',
        ],
        [
            'id' => 'q6_cognitive_stack_trace',
            'title' => 'Generate cognitive stack traces for every important Atlas decision',
            'detail' => 'Expose evidence, alternatives, agent debate, gates and discarded options behind routing and merge decisions.',
            'source' => 'app/Services/Ai/Cognition/AtlasCognitiveFunctionDecomposerService.php',
            'test' => 'AtlasCognitiveFunctionDecomposerServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_EVIDENCE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q6',
            'jump' => 'Trust and auditability jump because every decision becomes debuggable.',
            'attention' => 'Do not expose secrets or provider-private traces.',
        ],
        [
            'id' => 'q7_emergent_specification_engine',
            'title' => 'Let telemetry and user behavior generate spec proposals',
            'detail' => 'Invert product planning by turning real usage gaps, workarounds and support patterns into spec seeds.',
            'source' => 'app/Services/Ai/Product/AtlasProductDeliveryOutcomeMemoryService.php',
            'test' => 'AtlasProductDeliveryOutcomeMemoryServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_SELF_DIRECTED_EVOLUTION,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPLEMENTATION,
            'severity' => 'medium',
            'tier' => 'Q7',
            'jump' => 'The roadmap starts coming from reality, not speculation.',
            'attention' => 'Sensitive telemetry must pass consent and privacy gates.',
        ],
        [
            'id' => 'q8_inverse_engineering_layer',
            'title' => 'Translate desired outcomes into implementation constraints',
            'detail' => 'Let operators define p99, cost, reliability or compatibility outcomes and have Atlas derive candidate changes.',
            'source' => 'app/Services/Ai/Programming/ProgrammingPatchVerifier.php',
            'test' => 'ProgrammingPatchVerifierTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_ATLAS_DEV,
            'kind' => AreaFocusDeepFindingEngineService::KIND_RUNTIME,
            'severity' => 'medium',
            'tier' => 'Q8',
            'jump' => 'Precision rises because Atlas optimizes for outcome constraints instead of code guesses.',
            'attention' => 'Constraints must be measurable, otherwise execution blocks.',
        ],
        [
            'id' => 'q9_code_singularity_engine',
            'title' => 'Continuously collapse duplicate semantics into reusable primitives',
            'detail' => 'Detect semantic duplication and propose consolidation plans across services, tests and callers.',
            'source' => 'app/Services/Ai/Programming/ProgrammingSemanticCodeGraphService.php',
            'test' => 'ProgrammingSemanticCodeGraphServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPROVEMENT,
            'severity' => 'medium',
            'tier' => 'Q9',
            'jump' => 'Maintenance burden shrinks over time instead of growing with every feature.',
            'attention' => 'Consolidation must prove caller parity before merge.',
        ],
        [
            'id' => 'q10_cross_project_federation',
            'title' => 'Federate engineering learning across Atlas projects without data leakage',
            'detail' => 'Share sanitized learning capsules across server, mobile, desktop and infra so each project benefits from the others.',
            'source' => 'app/Services/Ai/Compounding/AtlasCompoundingEngineeringIntelligenceService.php',
            'test' => 'AtlasCompoundingEngineeringIntelligenceServiceTest.php',
            'owner' => AreaFocusDeepFindingEngineService::OWNER_FORGE,
            'kind' => AreaFocusDeepFindingEngineService::KIND_IMPROVEMENT,
            'severity' => 'medium',
            'tier' => 'Q10',
            'jump' => 'Atlas becomes a galaxy of projects learning as one organism.',
            'attention' => 'Sovereignty and sanitization gates are mandatory.',
        ],
    ];
}
